In [54]:
import geemap

In [339]:
Map = geemap.Map()
Map

Map(center=[0, 0], controls=(WidgetControl(options=['position', 'transparent_bg'], widget=SearchDataGUI(childrâ€¦

In [197]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat5 = ee.ImageCollection('LANDSAT/LT05/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B4', 'B3']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat5_with_ndvi = landsat5.map(calculate_ndvi)
    
    median_image = landsat5_with_ndvi.median()
    
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

start_date = '2008-01-01'
end_date = '2008-12-31'

ndvi_results = []

for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2008v2.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

KeyboardInterrupt:

In [196]:
coords_df = coords_df.drop(columns=['Unnamed: 0'])
coords_df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,6.03,295.3,50.3,D,0,0.180210
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,6.03,293.6,26.8,D,0,0.396002
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,6.03,292.1,21.7,D,0,0.155087
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,6.03,290.7,37.7,D,0,0.435763
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,6.03,294.7,20.8,D,0,0.168969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,61.03,295.7,71.2,D,0,0.279683
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,61.03,294.2,80.3,D,0,0.237406
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,61.03,293.5,49.8,D,0,0.333590
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,61.03,293.7,23.0,D,2,0.169533
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,61.03,293.7,18.2,D,2,0.542101

In [56]:
coords_df.to_csv('ndvi_results2008.csv')

In [57]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat5 = ee.ImageCollection('LANDSAT/LT05/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B4', 'B3']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat5_with_ndvi = landsat5.map(calculate_ndvi)
    
    median_image = landsat5_with_ndvi.median()
    
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

start_date = '2011-01-01'
end_date = '2011-12-31'

ndvi_results = []

for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2011.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.189403
1           D     0  0.541897
2           D     0  0.224645
3           D     0  0.520533
4           D     0  0.217550
...       ...   ...       ...
2686        D     0  0.352871
2687        D     0  0.291879
2688        D     0  0.389155
2689        D     2  0.237687
2690        D     2  0.503036

[2691 rows x 17 columns]

In [59]:
coords_df = coords_df.drop(columns=['Unnamed: 0'])
coords_df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,6.03,295.3,50.3,D,0,0.189403
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,6.03,293.6,26.8,D,0,0.541897
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,6.03,292.1,21.7,D,0,0.224645
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,6.03,290.7,37.7,D,0,0.520533
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,6.03,294.7,20.8,D,0,0.217550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,61.03,295.7,71.2,D,0,0.352871
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,61.03,294.2,80.3,D,0,0.291879
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,61.03,293.5,49.8,D,0,0.389155
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,61.03,293.7,23.0,D,2,0.237687
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,61.03,293.7,18.2,D,2,0.503036

In [60]:
coords_df.to_csv('ndvi_results2011.csv')

In [61]:
coords_df.columns

Index(['latitude', 'longitude', 'brightness', 'scan', 'track', 'acq_date',
       'acq_time', 'satellite', 'instrument', 'confidence', 'version',
       'bright_t31', 'frp', 'daynight', 'type', 'NDVI'],
      dtype='object')

In [62]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.189403
1      34.4592  -118.8596  0.541897
2      34.4609  -118.8706  0.224645
3      34.3317  -119.0296  0.520533
4      34.3298  -119.0179  0.217550
...        ...        ...       ...
2686   34.3057  -119.0683  0.352871
2687   34.3045  -119.0845  0.291879
2688   34.3039  -119.0913  0.389155
2689   34.2857  -119.1862  0.237687
2690   34.2872  -119.1750  0.503036

[2691 rows x 3 columns]

In [63]:
coords_df.to_csv('ndvi_results2011.csv')

In [64]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat5 = ee.ImageCollection('LANDSAT/LT05/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B4', 'B3']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat5_with_ndvi = landsat5.map(calculate_ndvi)
    
    median_image = landsat5_with_ndvi.median()
    
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

start_date = '2009-01-01'
end_date = '2009-12-31'

ndvi_results = []

for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2011.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.156365
1           D     0  0.415156
2           D     0  0.208393
3           D     0  0.542271
4           D     0  0.193320
...       ...   ...       ...
2686        D     0  0.354456
2687        D     0  0.270226
2688        D     0  0.333548
2689        D     2  0.234534
2690        D     2  0.522824

[2691 rows x 17 columns]

In [66]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.156365
1      34.4592  -118.8596  0.415156
2      34.4609  -118.8706  0.208393
3      34.3317  -119.0296  0.542271
4      34.3298  -119.0179  0.193320
...        ...        ...       ...
2686   34.3057  -119.0683  0.354456
2687   34.3045  -119.0845  0.270226
2688   34.3039  -119.0913  0.333548
2689   34.2857  -119.1862  0.234534
2690   34.2872  -119.1750  0.522824

[2691 rows x 3 columns]

In [67]:
coords_df.to_csv('ndvi_results2009.csv')

In [68]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat5 = ee.ImageCollection('LANDSAT/LT05/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B4', 'B3']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat5_with_ndvi = landsat5.map(calculate_ndvi)
    
    median_image = landsat5_with_ndvi.median()
    
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

start_date = '2010-01-01'
end_date = '2010-12-31'

ndvi_results = []

for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2010.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.175897
1           D     0  0.514810
2           D     0  0.202637
3           D     0  0.595262
4           D     0  0.198579
...       ...   ...       ...
2686        D     0  0.388149
2687        D     0  0.251372
2688        D     0  0.351903
2689        D     2  0.238830
2690        D     2  0.489521

[2691 rows x 17 columns]

In [69]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.175897
1      34.4592  -118.8596  0.514810
2      34.4609  -118.8706  0.202637
3      34.3317  -119.0296  0.595262
4      34.3298  -119.0179  0.198579
...        ...        ...       ...
2686   34.3057  -119.0683  0.388149
2687   34.3045  -119.0845  0.251372
2688   34.3039  -119.0913  0.351903
2689   34.2857  -119.1862  0.238830
2690   34.2872  -119.1750  0.489521

[2691 rows x 3 columns]

In [70]:
coords_df.to_csv('ndvi_results2010.csv')

In [73]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat5 = ee.ImageCollection('LANDSAT/LT05/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B4', 'B3']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat5_with_ndvi = landsat5.map(calculate_ndvi)
    
    median_image = landsat5_with_ndvi.median()
    
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

start_date = '2007-01-01'
end_date = '2007-12-31'

ndvi_results = []

for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2007.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.217757
1           D     0  0.415397
2           D     0  0.206314
3           D     0  0.466833
4           D     0  0.156980
...       ...   ...       ...
2686        D     0  0.255601
2687        D     0  0.206396
2688        D     0  0.264975
2689        D     2  0.209523
2690        D     2  0.495688

[2691 rows x 17 columns]

In [74]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.217757
1      34.4592  -118.8596  0.415397
2      34.4609  -118.8706  0.206314
3      34.3317  -119.0296  0.466833
4      34.3298  -119.0179  0.156980
...        ...        ...       ...
2686   34.3057  -119.0683  0.255601
2687   34.3045  -119.0845  0.206396
2688   34.3039  -119.0913  0.264975
2689   34.2857  -119.1862  0.209523
2690   34.2872  -119.1750  0.495688

[2691 rows x 3 columns]

In [75]:
coords_df.to_csv('ndvi_results2007.csv')

In [76]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

# Load CSV file from your local filesystem
csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv' 
coords_df = pd.read_csv(csv_file_path)

# Function to get NDVI for a given point using Landsat 8
def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat8 = ee.ImageCollection('LANDSAT/LC08/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    # Calculate NDVI for each image in the collection
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B5', 'B4']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat8_with_ndvi = landsat8.map(calculate_ndvi)
    
    # Reduce the collection to a single median image
    median_image = landsat8_with_ndvi.median()
    
    # Reduce the region
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

# Define the date range for the year 2014
start_date = '2014-01-01'
end_date = '2014-12-31'

# Initialize list to store NDVI results
ndvi_results = []

# Iterate through the coordinates and get NDVI
for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2014.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.157157
1           D     0  0.438695
2           D     0  0.237172
3           D     0  0.652562
4           D     0  0.179003
...       ...   ...       ...
2686        D     0  0.295810
2687        D     0  0.250739
2688        D     0  0.288442
2689        D     2  0.251938
2690        D     2  0.532252

[2691 rows x 17 columns]

In [77]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.157157
1      34.4592  -118.8596  0.438695
2      34.4609  -118.8706  0.237172
3      34.3317  -119.0296  0.652562
4      34.3298  -119.0179  0.179003
...        ...        ...       ...
2686   34.3057  -119.0683  0.295810
2687   34.3045  -119.0845  0.250739
2688   34.3039  -119.0913  0.288442
2689   34.2857  -119.1862  0.251938
2690   34.2872  -119.1750  0.532252

[2691 rows x 3 columns]

In [78]:
coords_df.to_csv('ndvi_results2014.csv')

In [79]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

# Load CSV file from your local filesystem
csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

# Function to get NDVI for a given point using Landsat 8
def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat8 = ee.ImageCollection('LANDSAT/LC08/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    # Calculate NDVI for each image in the collection
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B5', 'B4']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat8_with_ndvi = landsat8.map(calculate_ndvi)
    
    # Reduce the collection to a single median image
    median_image = landsat8_with_ndvi.median()
    
    # Reduce the region
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

# Define the date range for the year 2014
start_date = '2015-01-01'
end_date = '2015-12-31'

# Initialize list to store NDVI results
ndvi_results = []

# Iterate through the coordinates and get NDVI
for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2015.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.164241
1           D     0  0.465233
2           D     0  0.194229
3           D     0  0.680648
4           D     0  0.185394
...       ...   ...       ...
2686        D     0  0.307121
2687        D     0  0.220316
2688        D     0  0.256296
2689        D     2  0.228474
2690        D     2  0.567150

[2691 rows x 17 columns]

In [80]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.164241
1      34.4592  -118.8596  0.465233
2      34.4609  -118.8706  0.194229
3      34.3317  -119.0296  0.680648
4      34.3298  -119.0179  0.185394
...        ...        ...       ...
2686   34.3057  -119.0683  0.307121
2687   34.3045  -119.0845  0.220316
2688   34.3039  -119.0913  0.256296
2689   34.2857  -119.1862  0.228474
2690   34.2872  -119.1750  0.567150

[2691 rows x 3 columns]

In [81]:
coords_df.to_csv('ndvi_results2015.csv')

In [82]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

# Load CSV file from your local filesystem
csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'  
coords_df = pd.read_csv(csv_file_path)

# Function to get NDVI for a given point using Landsat 8
def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat8 = ee.ImageCollection('LANDSAT/LC08/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    # Calculate NDVI for each image in the collection
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B5', 'B4']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat8_with_ndvi = landsat8.map(calculate_ndvi)
    
    # Reduce the collection to a single median image
    median_image = landsat8_with_ndvi.median()
    
    # Reduce the region
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

# Define the date range for the year 2014
start_date = '2016-01-01'
end_date = '2016-12-31'

# Initialize list to store NDVI results
ndvi_results = []

# Iterate through the coordinates and get NDVI
for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2016.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.165583
1           D     0  0.413342
2           D     0  0.260472
3           D     0  0.611448
4           D     0  0.176777
...       ...   ...       ...
2686        D     0  0.364472
2687        D     0  0.238655
2688        D     0  0.285045
2689        D     2  0.233806
2690        D     2  0.559753

[2691 rows x 17 columns]

In [83]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.165583
1      34.4592  -118.8596  0.413342
2      34.4609  -118.8706  0.260472
3      34.3317  -119.0296  0.611448
4      34.3298  -119.0179  0.176777
...        ...        ...       ...
2686   34.3057  -119.0683  0.364472
2687   34.3045  -119.0845  0.238655
2688   34.3039  -119.0913  0.285045
2689   34.2857  -119.1862  0.233806
2690   34.2872  -119.1750  0.559753

[2691 rows x 3 columns]

In [84]:
coords_df.to_csv('ndvi_results2016.csv')

In [85]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

# Load CSV file from your local filesystem
csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv' 
coords_df = pd.read_csv(csv_file_path)

# Function to get NDVI for a given point using Landsat 8
def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat8 = ee.ImageCollection('LANDSAT/LC08/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    # Calculate NDVI for each image in the collection
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B5', 'B4']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat8_with_ndvi = landsat8.map(calculate_ndvi)
    
    # Reduce the collection to a single median image
    median_image = landsat8_with_ndvi.median()
    
    # Reduce the region
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

# Define the date range for the year 2014
start_date = '2017-01-01'
end_date = '2017-12-31'

# Initialize list to store NDVI results
ndvi_results = []

# Iterate through the coordinates and get NDVI
for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2017.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.122865
1           D     0  0.455834
2           D     0  0.206686
3           D     0  0.640159
4           D     0  0.192174
...       ...   ...       ...
2686        D     0  0.415602
2687        D     0  0.290165
2688        D     0  0.312699
2689        D     2  0.254468
2690        D     2  0.559743

[2691 rows x 17 columns]

In [86]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.122865
1      34.4592  -118.8596  0.455834
2      34.4609  -118.8706  0.206686
3      34.3317  -119.0296  0.640159
4      34.3298  -119.0179  0.192174
...        ...        ...       ...
2686   34.3057  -119.0683  0.415602
2687   34.3045  -119.0845  0.290165
2688   34.3039  -119.0913  0.312699
2689   34.2857  -119.1862  0.254468
2690   34.2872  -119.1750  0.559743

[2691 rows x 3 columns]

In [87]:
coords_df.to_csv('ndvi_results2017.csv')

In [88]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

# Load CSV file from your local filesystem
csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv' 
coords_df = pd.read_csv(csv_file_path)

# Function to get NDVI for a given point using Landsat 8
def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat8 = ee.ImageCollection('LANDSAT/LC08/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    # Calculate NDVI for each image in the collection
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B5', 'B4']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat8_with_ndvi = landsat8.map(calculate_ndvi)
    
    # Reduce the collection to a single median image
    median_image = landsat8_with_ndvi.median()
    
    # Reduce the region
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

# Define the date range for the year 2014
start_date = '2018-01-01'
end_date = '2018-12-31'

# Initialize list to store NDVI results
ndvi_results = []

# Iterate through the coordinates and get NDVI
for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2018.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.122615
1           D     0  0.516385
2           D     0  0.239091
3           D     0  0.535076
4           D     0  0.177058
...       ...   ...       ...
2686        D     0  0.345153
2687        D     0  0.293229
2688        D     0  0.275955
2689        D     2  0.261212
2690        D     2  0.602640

[2691 rows x 17 columns]

In [89]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.122615
1      34.4592  -118.8596  0.516385
2      34.4609  -118.8706  0.239091
3      34.3317  -119.0296  0.535076
4      34.3298  -119.0179  0.177058
...        ...        ...       ...
2686   34.3057  -119.0683  0.345153
2687   34.3045  -119.0845  0.293229
2688   34.3039  -119.0913  0.275955
2689   34.2857  -119.1862  0.261212
2690   34.2872  -119.1750  0.602640

[2691 rows x 3 columns]

In [90]:
coords_df.to_csv('ndvi_results2018.csv')

In [91]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

# Load CSV file from your local filesystem
csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

# Function to get NDVI for a given point using Landsat 8
def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat8 = ee.ImageCollection('LANDSAT/LC08/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    # Calculate NDVI for each image in the collection
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B5', 'B4']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat8_with_ndvi = landsat8.map(calculate_ndvi)
    
    # Reduce the collection to a single median image
    median_image = landsat8_with_ndvi.median()
    
    # Reduce the region
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

# Define the date range for the year 2014
start_date = '2019-01-01'
end_date = '2019-12-31'

# Initialize list to store NDVI results
ndvi_results = []

# Iterate through the coordinates and get NDVI
for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2019.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.113362
1           D     0  0.562387
2           D     0  0.229873
3           D     0  0.596800
4           D     0  0.227133
...       ...   ...       ...
2686        D     0  0.375557
2687        D     0  0.279957
2688        D     0  0.305564
2689        D     2  0.276776
2690        D     2  0.579781

[2691 rows x 17 columns]

In [92]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.113362
1      34.4592  -118.8596  0.562387
2      34.4609  -118.8706  0.229873
3      34.3317  -119.0296  0.596800
4      34.3298  -119.0179  0.227133
...        ...        ...       ...
2686   34.3057  -119.0683  0.375557
2687   34.3045  -119.0845  0.279957
2688   34.3039  -119.0913  0.305564
2689   34.2857  -119.1862  0.276776
2690   34.2872  -119.1750  0.579781

[2691 rows x 3 columns]

In [94]:
coords_df.to_csv('ndvi_results2019.csv')

In [95]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

# Load CSV file from your local filesystem
csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

# Function to get NDVI for a given point using Landsat 8
def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat8 = ee.ImageCollection('LANDSAT/LC08/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    # Calculate NDVI for each image in the collection
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B5', 'B4']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat8_with_ndvi = landsat8.map(calculate_ndvi)
    
    # Reduce the collection to a single median image
    median_image = landsat8_with_ndvi.median()
    
    # Reduce the region
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

# Define the date range for the year 2014
start_date = '2020-01-01'
end_date = '2020-12-31'

# Initialize list to store NDVI results
ndvi_results = []

# Iterate through the coordinates and get NDVI
for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2020.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.188768
1           D     0  0.535325
2           D     0  0.225967
3           D     0  0.453410
4           D     0  0.230021
...       ...   ...       ...
2686        D     0  0.269576
2687        D     0  0.237036
2688        D     0  0.296960
2689        D     2  0.261154
2690        D     2  0.578496

[2691 rows x 17 columns]

In [96]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.188768
1      34.4592  -118.8596  0.535325
2      34.4609  -118.8706  0.225967
3      34.3317  -119.0296  0.453410
4      34.3298  -119.0179  0.230021
...        ...        ...       ...
2686   34.3057  -119.0683  0.269576
2687   34.3045  -119.0845  0.237036
2688   34.3039  -119.0913  0.296960
2689   34.2857  -119.1862  0.261154
2690   34.2872  -119.1750  0.578496

[2691 rows x 3 columns]

In [97]:
coords_df.to_csv('ndvi_results2020.csv')

In [98]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

# Load CSV file from your local filesystem
csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'  
coords_df = pd.read_csv(csv_file_path)

# Function to get NDVI for a given point using Landsat 8
def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat8 = ee.ImageCollection('LANDSAT/LC08/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    # Calculate NDVI for each image in the collection
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B5', 'B4']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat8_with_ndvi = landsat8.map(calculate_ndvi)
    
    # Reduce the collection to a single median image
    median_image = landsat8_with_ndvi.median()
    
    # Reduce the region
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

# Define the date range for the year 2014
start_date = '2021-01-01'
end_date = '2021-12-31'

# Initialize list to store NDVI results
ndvi_results = []

# Iterate through the coordinates and get NDVI
for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2021.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.245536
1           D     0  0.402140
2           D     0  0.223771
3           D     0  0.317880
4           D     0  0.170219
...       ...   ...       ...
2686        D     0  0.182947
2687        D     0  0.193116
2688        D     0  0.234675
2689        D     2  0.242923
2690        D     2  0.559918

[2691 rows x 17 columns]

In [99]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.245536
1      34.4592  -118.8596  0.402140
2      34.4609  -118.8706  0.223771
3      34.3317  -119.0296  0.317880
4      34.3298  -119.0179  0.170219
...        ...        ...       ...
2686   34.3057  -119.0683  0.182947
2687   34.3045  -119.0845  0.193116
2688   34.3039  -119.0913  0.234675
2689   34.2857  -119.1862  0.242923
2690   34.2872  -119.1750  0.559918

[2691 rows x 3 columns]

In [100]:
coords_df.to_csv('ndvi_results2021.csv')

In [103]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

# Load CSV file from your local filesystem
csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

# Function to get NDVI for a given point using Landsat 8
def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat8 = ee.ImageCollection('LANDSAT/LC08/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    # Calculate NDVI for each image in the collection
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B5', 'B4']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat8_with_ndvi = landsat8.map(calculate_ndvi)
    
    # Reduce the collection to a single median image
    median_image = landsat8_with_ndvi.median()
    
    # Reduce the region
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

# Define the date range for the year 2014
start_date = '2013-01-01'
end_date = '2013-12-31'

# Initialize list to store NDVI results
ndvi_results = []

# Iterate through the coordinates and get NDVI
for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2013.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.322997
1           D     0  0.451160
2           D     0  0.241785
3           D     0  0.581933
4           D     0  0.176687
...       ...   ...       ...
2686        D     0  0.261303
2687        D     0  0.219594
2688        D     0  0.289662
2689        D     2  0.266825
2690        D     2  0.525106

[2691 rows x 17 columns]

In [104]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.322997
1      34.4592  -118.8596  0.451160
2      34.4609  -118.8706  0.241785
3      34.3317  -119.0296  0.581933
4      34.3298  -119.0179  0.176687
...        ...        ...       ...
2686   34.3057  -119.0683  0.261303
2687   34.3045  -119.0845  0.219594
2688   34.3039  -119.0913  0.289662
2689   34.2857  -119.1862  0.266825
2690   34.2872  -119.1750  0.525106

[2691 rows x 3 columns]

In [105]:
coords_df.to_csv('ndvi_results2013.csv')

In [106]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

# Load CSV file from your local filesystem
csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

# Function to get NDVI for a given point using Landsat 8 and Landsat 9
def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat8_9 = ee.ImageCollection('LANDSAT/LC08/C01/T1_SR') \
        .merge(ee.ImageCollection('LANDSAT/LC09/C02/T1_L2')) \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    # Calculate NDVI for each image in the collection
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['SR_B5', 'SR_B4']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat8_9_with_ndvi = landsat8_9.map(calculate_ndvi)
    
    # Reduce the collection to a single median image
    median_image = landsat8_9_with_ndvi.median()
    
    # Reduce the region
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

# Define the date range for 2022-2024
start_date = '2022-01-01'
end_date = '2022-12-31'

# Initialize list to store NDVI results
ndvi_results = []

# Iterate through the coordinates and get NDVI
for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2022.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.057681
1           D     0  0.202682
2           D     0  0.112112
3           D     0  0.133303
4           D     0  0.116826
...       ...   ...       ...
2686        D     0  0.162953
2687        D     0  0.125251
2688        D     0  0.124069
2689        D     2  0.109967
2690        D     2  0.248984

[2691 rows x 17 columns]

In [107]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.057681
1      34.4592  -118.8596  0.202682
2      34.4609  -118.8706  0.112112
3      34.3317  -119.0296  0.133303
4      34.3298  -119.0179  0.116826
...        ...        ...       ...
2686   34.3057  -119.0683  0.162953
2687   34.3045  -119.0845  0.125251
2688   34.3039  -119.0913  0.124069
2689   34.2857  -119.1862  0.109967
2690   34.2872  -119.1750  0.248984

[2691 rows x 3 columns]

In [108]:
coords_df.to_csv('ndvi_results2022.csv')

In [109]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

# Load CSV file from your local filesystem
csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

# Function to get NDVI for a given point using Landsat 8 and Landsat 9
def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat8_9 = ee.ImageCollection('LANDSAT/LC08/C01/T1_SR') \
        .merge(ee.ImageCollection('LANDSAT/LC09/C02/T1_L2')) \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    # Calculate NDVI for each image in the collection
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['SR_B5', 'SR_B4']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat8_9_with_ndvi = landsat8_9.map(calculate_ndvi)
    
    # Reduce the collection to a single median image
    median_image = landsat8_9_with_ndvi.median()
    
    # Reduce the region
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

# Define the date range for 2022-2024
start_date = '2023-01-01'
end_date = '2023-12-31'

# Initialize list to store NDVI results
ndvi_results = []

# Iterate through the coordinates and get NDVI
for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2023.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.117107
1           D     0  0.180689
2           D     0  0.123683
3           D     0  0.137608
4           D     0  0.126685
...       ...   ...       ...
2686        D     0  0.194529
2687        D     0  0.173666
2688        D     0  0.148173
2689        D     2  0.123252
2690        D     2  0.251813

[2691 rows x 17 columns]

In [110]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.117107
1      34.4592  -118.8596  0.180689
2      34.4609  -118.8706  0.123683
3      34.3317  -119.0296  0.137608
4      34.3298  -119.0179  0.126685
...        ...        ...       ...
2686   34.3057  -119.0683  0.194529
2687   34.3045  -119.0845  0.173666
2688   34.3039  -119.0913  0.148173
2689   34.2857  -119.1862  0.123252
2690   34.2872  -119.1750  0.251813

[2691 rows x 3 columns]

In [111]:
coords_df.to_csv('ndvi_results2023.csv')

In [112]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat5 = ee.ImageCollection('LANDSAT/LT05/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B4', 'B3']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat5_with_ndvi = landsat5.map(calculate_ndvi)
    
    median_image = landsat5_with_ndvi.median()
    
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

start_date = '2006-01-01'
end_date = '2006-12-31'

ndvi_results = []

for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2006.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.092687
1           D     0  0.439264
2           D     0  0.197131
3           D     0  0.489130
4           D     0  0.156078
...       ...   ...       ...
2686        D     0  0.285769
2687        D     0  0.238492
2688        D     0  0.326463
2689        D     2  0.199776
2690        D     2  0.513483

[2691 rows x 17 columns]

In [113]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.092687
1      34.4592  -118.8596  0.439264
2      34.4609  -118.8706  0.197131
3      34.3317  -119.0296  0.489130
4      34.3298  -119.0179  0.156078
...        ...        ...       ...
2686   34.3057  -119.0683  0.285769
2687   34.3045  -119.0845  0.238492
2688   34.3039  -119.0913  0.326463
2689   34.2857  -119.1862  0.199776
2690   34.2872  -119.1750  0.513483

[2691 rows x 3 columns]

In [114]:
coords_df.to_csv('ndvi_results2006.csv')

In [115]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat5 = ee.ImageCollection('LANDSAT/LT05/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B4', 'B3']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat5_with_ndvi = landsat5.map(calculate_ndvi)
    
    median_image = landsat5_with_ndvi.median()
    
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

start_date = '2005-01-01'
end_date = '2005-12-31'

ndvi_results = []

for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2005.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.055329
1           D     0  0.504999
2           D     0  0.259487
3           D     0  0.532182
4           D     0  0.187256
...       ...   ...       ...
2686        D     0  0.334356
2687        D     0  0.275026
2688        D     0  0.295847
2689        D     2  0.200573
2690        D     2  0.497478

[2691 rows x 17 columns]

In [116]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.055329
1      34.4592  -118.8596  0.504999
2      34.4609  -118.8706  0.259487
3      34.3317  -119.0296  0.532182
4      34.3298  -119.0179  0.187256
...        ...        ...       ...
2686   34.3057  -119.0683  0.334356
2687   34.3045  -119.0845  0.275026
2688   34.3039  -119.0913  0.295847
2689   34.2857  -119.1862  0.200573
2690   34.2872  -119.1750  0.497478

[2691 rows x 3 columns]

In [117]:
coords_df.to_csv('ndvi_results2005.csv')

In [126]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat5 = ee.ImageCollection('LANDSAT/LT05/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B4', 'B3']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat5_with_ndvi = landsat5.map(calculate_ndvi)
    
    median_image = landsat5_with_ndvi.median()
    
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

start_date = '2004-01-01'
end_date = '2004-12-31'

ndvi_results = []

for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2004.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.200820
1           D     0  0.331276
2           D     0  0.210924
3           D     0  0.477115
4           D     0  0.165291
...       ...   ...       ...
2686        D     0  0.232851
2687        D     0  0.248821
2688        D     0  0.235585
2689        D     2  0.207876
2690        D     2  0.516628

[2691 rows x 17 columns]

In [127]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.200820
1      34.4592  -118.8596  0.331276
2      34.4609  -118.8706  0.210924
3      34.3317  -119.0296  0.477115
4      34.3298  -119.0179  0.165291
...        ...        ...       ...
2686   34.3057  -119.0683  0.232851
2687   34.3045  -119.0845  0.248821
2688   34.3039  -119.0913  0.235585
2689   34.2857  -119.1862  0.207876
2690   34.2872  -119.1750  0.516628

[2691 rows x 3 columns]

In [129]:
coords_df.to_csv('ndvi_results2004.csv')

In [121]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat5 = ee.ImageCollection('LANDSAT/LT05/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B4', 'B3']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat5_with_ndvi = landsat5.map(calculate_ndvi)
    
    median_image = landsat5_with_ndvi.median()
    
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

start_date = '2003-01-01'
end_date = '2003-12-31'

ndvi_results = []

for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2003.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.239830
1           D     0  0.525469
2           D     0  0.201397
3           D     0  0.537519
4           D     0  0.180771
...       ...   ...       ...
2686        D     0  0.277882
2687        D     0  0.243622
2688        D     0  0.311972
2689        D     2  0.198719
2690        D     2  0.535394

[2691 rows x 17 columns]

In [123]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.239830
1      34.4592  -118.8596  0.525469
2      34.4609  -118.8706  0.201397
3      34.3317  -119.0296  0.537519
4      34.3298  -119.0179  0.180771
...        ...        ...       ...
2686   34.3057  -119.0683  0.277882
2687   34.3045  -119.0845  0.243622
2688   34.3039  -119.0913  0.311972
2689   34.2857  -119.1862  0.198719
2690   34.2872  -119.1750  0.535394

[2691 rows x 3 columns]

In [124]:
coords_df.to_csv('ndvi_results2003.csv')

In [125]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat5 = ee.ImageCollection('LANDSAT/LT05/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B4', 'B3']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat5_with_ndvi = landsat5.map(calculate_ndvi)
    
    median_image = landsat5_with_ndvi.median()
    
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

start_date = '2002-01-01'
end_date = '2002-12-31'

ndvi_results = []

for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2002.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.207247
1           D     0  0.421418
2           D     0  0.187728
3           D     0  0.433419
4           D     0  0.161847
...       ...   ...       ...
2686        D     0  0.243872
2687        D     0  0.193867
2688        D     0  0.252774
2689        D     2  0.189498
2690        D     2  0.517409

[2691 rows x 17 columns]

In [130]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.200820
1      34.4592  -118.8596  0.331276
2      34.4609  -118.8706  0.210924
3      34.3317  -119.0296  0.477115
4      34.3298  -119.0179  0.165291
...        ...        ...       ...
2686   34.3057  -119.0683  0.232851
2687   34.3045  -119.0845  0.248821
2688   34.3039  -119.0913  0.235585
2689   34.2857  -119.1862  0.207876
2690   34.2872  -119.1750  0.516628

[2691 rows x 3 columns]

In [131]:
coords_df.to_csv('ndvi_results2002.csv')

In [132]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat5 = ee.ImageCollection('LANDSAT/LT05/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B4', 'B3']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat5_with_ndvi = landsat5.map(calculate_ndvi)
    
    median_image = landsat5_with_ndvi.median()
    
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

start_date = '2001-01-01'
end_date = '2001-12-31'

ndvi_results = []

for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2001.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.198146
1           D     0  0.484689
2           D     0  0.212678
3           D     0  0.346661
4           D     0  0.198264
...       ...   ...       ...
2686        D     0  0.308845
2687        D     0  0.262563
2688        D     0  0.356757
2689        D     2  0.191063
2690        D     2  0.502688

[2691 rows x 17 columns]

In [133]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.198146
1      34.4592  -118.8596  0.484689
2      34.4609  -118.8706  0.212678
3      34.3317  -119.0296  0.346661
4      34.3298  -119.0179  0.198264
...        ...        ...       ...
2686   34.3057  -119.0683  0.308845
2687   34.3045  -119.0845  0.262563
2688   34.3039  -119.0913  0.356757
2689   34.2857  -119.1862  0.191063
2690   34.2872  -119.1750  0.502688

[2691 rows x 3 columns]

In [134]:
coords_df.to_csv('ndvi_results2001.csv')

In [177]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat5 = ee.ImageCollection('LANDSAT/LT05/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B4', 'B3']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat5_with_ndvi = landsat5.map(calculate_ndvi)
    
    median_image = landsat5_with_ndvi.median()
    
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

start_date = '2000-01-01'
end_date = '2000-12-31'

ndvi_results = []

for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2000v2.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.180210
1           D     0  0.396002
2           D     0  0.155087
3           D     0  0.435763
4           D     0  0.168969
...       ...   ...       ...
2686        D     0  0.279683
2687        D     0  0.237406
2688        D     0  0.333590
2689        D     2  0.169533
2690        D     2  0.542101

[2691 rows x 17 columns]

In [136]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df

      latitude  longitude      NDVI
0      34.3716  -118.9757  0.180210
1      34.4592  -118.8596  0.396002
2      34.4609  -118.8706  0.155087
3      34.3317  -119.0296  0.435763
4      34.3298  -119.0179  0.168969
...        ...        ...       ...
2686   34.3057  -119.0683  0.279683
2687   34.3045  -119.0845  0.237406
2688   34.3039  -119.0913  0.333590
2689   34.2857  -119.1862  0.169533
2690   34.2872  -119.1750  0.542101

[2691 rows x 3 columns]

In [137]:
coords_df.to_csv('ndvi_results2000.csv')

In [138]:
import ee
import pandas as pd

# Authenticate and initialize the Earth Engine library
ee.Authenticate()
ee.Initialize()

csv_file_path = '/Users/rohan/fire_archive_M-C61_481023_filtered.csv'
coords_df = pd.read_csv(csv_file_path)

def get_ndvi(lat, lon, start_date, end_date):
    point = ee.Geometry.Point(lon, lat)
    landsat5 = ee.ImageCollection('LANDSAT/LT05/C01/T1_SR') \
        .filterBounds(point) \
        .filterDate(start_date, end_date)
    
    def calculate_ndvi(image):
        ndvi = image.normalizedDifference(['B4', 'B3']).rename('NDVI')
        return image.addBands(ndvi)
    
    landsat5_with_ndvi = landsat5.map(calculate_ndvi)
    
    median_image = landsat5_with_ndvi.median()
    
    ndvi_values = median_image.select('NDVI').reduceRegion(
        reducer=ee.Reducer.median(),
        geometry=point,
        scale=30
    )
    
    return ndvi_values.get('NDVI').getInfo()

start_date = '2002-01-01'
end_date = '2002-12-31'

ndvi_results = []

for index, row in coords_df.iterrows():
    lat = row['latitude']
    lon = row['longitude']
    try:
        ndvi_value = get_ndvi(lat, lon, start_date, end_date)
    except Exception as e:
        ndvi_value = None
        print(f"Error processing point ({lat}, {lon}): {e}")
    ndvi_results.append(ndvi_value)

# Add NDVI results to the DataFrame
coords_df['NDVI'] = ndvi_results

# Save the results to a new CSV file
coords_df.to_csv('ndvi_results2002.csv', index=False)

# Print the resulting DataFrame
print(coords_df)

      Unnamed: 0  latitude  longitude  brightness  scan  track    acq_date  \
0              2   34.3716  -118.9757       323.1   2.0    1.4  2000-11-28
1              4   34.4592  -118.8596       328.5   1.0    1.0  2000-12-18
2              6   34.4609  -118.8706       324.4   1.0    1.0  2000-12-18
3              7   34.3317  -119.0296       333.3   1.1    1.1  2000-12-25
4              9   34.3298  -119.0179       321.1   1.1    1.1  2000-12-25
...          ...       ...        ...         ...   ...    ...         ...
2686        4110   34.3057  -119.0683       325.7   2.3    1.5  2023-12-09
2687        4112   34.3045  -119.0845       327.8   2.3    1.5  2023-12-09
2688        4114   34.3039  -119.0913       319.8   2.3    1.5  2023-12-09
2689        4119   34.2857  -119.1862       326.0   1.1    1.0  2024-02-13
2690        4121   34.2872  -119.1750       321.8   1.1    1.0  2024-02-13

      acq_time satellite instrument  confidence  version  bright_t31   frp  \
0         1929     Terra      MODIS          80     6.03       295.3  50.3
1         1904     Terra      MODIS          86     6.03       293.6  26.8
2         1904     Terra      MODIS          83     6.03       292.1  21.7
3         1910     Terra      MODIS          88     6.03       290.7  37.7
4         1910     Terra      MODIS          81     6.03       294.7  20.8
...        ...       ...        ...         ...      ...         ...   ...
2686      2202      Aqua      MODIS          84    61.03       295.7  71.2
2687      2202      Aqua      MODIS          85    61.03       294.2  80.3
2688      2202      Aqua      MODIS          75    61.03       293.5  49.8
2689      2142      Aqua      MODIS          83    61.03       293.7  23.0
2690      2142      Aqua      MODIS          80    61.03       293.7  18.2

     daynight  type      NDVI
0           D     0  0.207247
1           D     0  0.421418
2           D     0  0.187728
3           D     0  0.433419
4           D     0  0.161847
...       ...   ...       ...
2686        D     0  0.243872
2687        D     0  0.193867
2688        D     0  0.252774
2689        D     2  0.189498
2690        D     2  0.517409

[2691 rows x 17 columns]

In [139]:
coords_df = coords_df[['latitude', 'longitude', 'NDVI']]
coords_df.to_csv('ndvi_results2002.csv')

In [144]:
file_path = '/Users/rohan/veryhot.csv'
veryhot = pd.read_csv(file_path)
veryhot

,Unnamed: 0,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,290,34.3543,-118.8883,418.7,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,308.2,1457.0,N,0
1,313,34.3724,-118.8334,453.3,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,322.4,2905.3,N,0
2,316,34.3864,-118.8320,406.2,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,301.5,1119.1,N,0
3,317,34.3788,-118.8383,466.1,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,323.7,3635.3,N,0
4,322,34.3754,-118.8731,396.8,3.0,1.7,2003-10-26,911,Aqua,MODIS,100,6.03,303.0,1162.5,N,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,3869,34.1044,-118.9523,500.0,1.0,1.0,2018-11-11,1846,Terra,MODIS,100,6.03,364.2,1605.6,D,0
149,3870,34.1060,-118.9631,500.0,1.0,1.0,2018-11-11,1846,Terra,MODIS,100,6.03,349.5,1608.1,D,0
150,3873,34.1133,-118.9504,474.0,1.0,1.0,2018-11-11,1846,Terra,MODIS,100,6.03,348.9,1074.0,D,0
151,3955,34.3331,-119.0557,452.8,2.0,1.4,2019-11-01,535,Terra,MODIS,100,6.03,315.3,2075.5,N,2
152,3958,34.3376,-119.0338,419.4,2.0,1.4,2019-11-01,535,Terra,MODIS,100,6.03,304.4,1081.1,N,2

In [146]:
veryhot = veryhot.drop(columns=['Unnamed: 0'])
veryhot

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,34.3543,-118.8883,418.7,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,308.2,1457.0,N,0
1,34.3724,-118.8334,453.3,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,322.4,2905.3,N,0
2,34.3864,-118.8320,406.2,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,301.5,1119.1,N,0
3,34.3788,-118.8383,466.1,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,323.7,3635.3,N,0
4,34.3754,-118.8731,396.8,3.0,1.7,2003-10-26,911,Aqua,MODIS,100,6.03,303.0,1162.5,N,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,34.1044,-118.9523,500.0,1.0,1.0,2018-11-11,1846,Terra,MODIS,100,6.03,364.2,1605.6,D,0
149,34.1060,-118.9631,500.0,1.0,1.0,2018-11-11,1846,Terra,MODIS,100,6.03,349.5,1608.1,D,0
150,34.1133,-118.9504,474.0,1.0,1.0,2018-11-11,1846,Terra,MODIS,100,6.03,348.9,1074.0,D,0
151,34.3331,-119.0557,452.8,2.0,1.4,2019-11-01,535,Terra,MODIS,100,6.03,315.3,2075.5,N,2
152,34.3376,-119.0338,419.4,2.0,1.4,2019-11-01,535,Terra,MODIS,100,6.03,304.4,1081.1,N,2

In [148]:
veryhot2003 = veryhot[veryhot['acq_date'].str[:4] == '2003']
veryhot2003

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,34.3543,-118.8883,418.7,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,308.2,1457.0,N,0
1,34.3724,-118.8334,453.3,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,322.4,2905.3,N,0
2,34.3864,-118.8320,406.2,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,301.5,1119.1,N,0
3,34.3788,-118.8383,466.1,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,323.7,3635.3,N,0
4,34.3754,-118.8731,396.8,3.0,1.7,2003-10-26,911,Aqua,MODIS,100,6.03,303.0,1162.5,N,0
5,34.4893,-118.8444,397.5,4.7,2.0,2003-10-26,2013,Aqua,MODIS,100,6.03,307.5,2167.6,D,0
6,34.5005,-118.8091,393.9,4.6,2.0,2003-10-26,2013,Aqua,MODIS,100,6.03,315.1,1961.4,D,0
7,34.4830,-118.7947,374.2,4.6,2.0,2003-10-26,2013,Aqua,MODIS,75,6.03,309.5,1154.8,D,0
8,34.4829,-118.7974,378.1,4.6,2.0,2003-10-26,2013,Aqua,MODIS,87,6.03,309.3,1289.0,D,0
9,34.5007,-118.8007,399.5,4.6,2.0,2003-10-26,2013,Aqua,MODIS,94,6.03,312.8,2248.5,D,0
10,34.4504,-118.8493,396.0,4.1,1.9,2003-10-26,2151,Aqua,MODIS,100,6.03,305.1,1688.3,D,0
11,34.4527,-118.8046,406.6,4.1,1.9,2003-10-26,2151,Aqua,MODIS,94,6.03,302.8,2197.5,D,0
12,34.4579,-118.8149,417.8,4.1,1.9,2003-10-26,2151,Aqua,MODIS,94,6.03,311.1,2823.3,D,0
13,34.4748,-118.8156,422.1,4.1,1.9,2003-10-26,2151,Aqua,MODIS,94,6.03,317.3,3102.1,D,0
14,34.4670,-118.8555,398.5,4.1,1.9,2003-10-26,2151,Aqua,MODIS,100,6.03,312.3,1791.5,D,0
15,34.4696,-118.8052,428.1,4.1,1.9,2003-10-26,2151,Aqua,MODIS,87,6.03,315.9,3526.2,D,0
16,34.4654,-118.9101,406.2,2.5,1.5,2003-10-27,1922,Terra,MODIS,100,6.03,312.6,1080.6,D,2
17,34.4648,-118.9138,484.6,1.1,1.0,2003-10-27,2056,Aqua,MODIS,100,6.03,341.4,1439.9,D,2
18,34.4742,-118.9153,500.1,1.1,1.0,2003-10-27,2056,Aqua,MODIS,100,6.03,400.1,1825.9,D,0
19,34.4761,-118.9034,488.0,1.1,1.0,2003-10-27,2056,Aqua,MODIS,100,6.03,326.0,1519.8,D,0
20,34.4668,-118.9015,480.0,1.1,1.0,2003-10-27,2056,Aqua,MODIS,100,6.03,330.8,1337.5,D,2
21,34.4723,-118.9270,474.4,1.1,1.0,2003-10-27,2056,Aqua,MODIS,100,6.03,317.9,1224.3,D,0
22,34.5046,-118.8849,438.5,1.5,1.2,2003-10-28,1827,Terra,MODIS,100,6.03,322.7,1040.2,D,0
23,34.5059,-118.8767,477.7,1.5,1.2,2003-10-28,1827,Terra,MODIS,100,6.03,338.4,2114.3,D,0
24,34.5026,-118.8664,447.0,1.5,1.2,2003-10-28,1827,Terra,MODIS,100,6.03,329.4,1226.5,D,0
25,34.5169,-118.9164,434.4,2.5,1.5,2003-10-28,2139,Aqua,MODIS,100,6.03,310.0,2014.4,D,0

In [151]:
ndvi_results2000 = pd.read_csv('/Users/rohan/ndvi_results2000.csv')
ndvi_results2000

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.180210
1              1   34.4592  -118.8596  0.396002
2              2   34.4609  -118.8706  0.155087
3              3   34.3317  -119.0296  0.435763
4              4   34.3298  -119.0179  0.168969
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.279683
2687        2687   34.3045  -119.0845  0.237406
2688        2688   34.3039  -119.0913  0.333590
2689        2689   34.2857  -119.1862  0.169533
2690        2690   34.2872  -119.1750  0.542101

[2691 rows x 4 columns]

In [152]:
ndvi_results2001 = pd.read_csv('/Users/rohan/ndvi_results2001.csv')
ndvi_results2001

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.198146
1              1   34.4592  -118.8596  0.484689
2              2   34.4609  -118.8706  0.212678
3              3   34.3317  -119.0296  0.346661
4              4   34.3298  -119.0179  0.198264
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.308845
2687        2687   34.3045  -119.0845  0.262563
2688        2688   34.3039  -119.0913  0.356757
2689        2689   34.2857  -119.1862  0.191063
2690        2690   34.2872  -119.1750  0.502688

[2691 rows x 4 columns]

In [153]:
ndvi_results2002 = pd.read_csv('/Users/rohan/ndvi_results2002.csv')
ndvi_results2002

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.207247
1              1   34.4592  -118.8596  0.421418
2              2   34.4609  -118.8706  0.187728
3              3   34.3317  -119.0296  0.433419
4              4   34.3298  -119.0179  0.161847
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.243872
2687        2687   34.3045  -119.0845  0.193867
2688        2688   34.3039  -119.0913  0.252774
2689        2689   34.2857  -119.1862  0.189498
2690        2690   34.2872  -119.1750  0.517409

[2691 rows x 4 columns]

In [154]:
ndvi_results2003 = pd.read_csv('/Users/rohan/ndvi_results2003.csv')
ndvi_results2003

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.239830
1              1   34.4592  -118.8596  0.525469
2              2   34.4609  -118.8706  0.201397
3              3   34.3317  -119.0296  0.537519
4              4   34.3298  -119.0179  0.180771
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.277882
2687        2687   34.3045  -119.0845  0.243622
2688        2688   34.3039  -119.0913  0.311972
2689        2689   34.2857  -119.1862  0.198719
2690        2690   34.2872  -119.1750  0.535394

[2691 rows x 4 columns]

In [155]:
ndvi_results2004 = pd.read_csv('/Users/rohan/ndvi_results2004.csv')
ndvi_results2004

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.200820
1              1   34.4592  -118.8596  0.331276
2              2   34.4609  -118.8706  0.210924
3              3   34.3317  -119.0296  0.477115
4              4   34.3298  -119.0179  0.165291
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.232851
2687        2687   34.3045  -119.0845  0.248821
2688        2688   34.3039  -119.0913  0.235585
2689        2689   34.2857  -119.1862  0.207876
2690        2690   34.2872  -119.1750  0.516628

[2691 rows x 4 columns]

In [156]:
ndvi_results2005 = pd.read_csv('/Users/rohan/ndvi_results2005.csv')
ndvi_results2005

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.055329
1              1   34.4592  -118.8596  0.504999
2              2   34.4609  -118.8706  0.259487
3              3   34.3317  -119.0296  0.532182
4              4   34.3298  -119.0179  0.187256
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.334356
2687        2687   34.3045  -119.0845  0.275026
2688        2688   34.3039  -119.0913  0.295847
2689        2689   34.2857  -119.1862  0.200573
2690        2690   34.2872  -119.1750  0.497478

[2691 rows x 4 columns]

In [157]:
ndvi_results2006 = pd.read_csv('/Users/rohan/ndvi_results2006.csv')
ndvi_results2006

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.092687
1              1   34.4592  -118.8596  0.439264
2              2   34.4609  -118.8706  0.197131
3              3   34.3317  -119.0296  0.489130
4              4   34.3298  -119.0179  0.156078
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.285769
2687        2687   34.3045  -119.0845  0.238492
2688        2688   34.3039  -119.0913  0.326463
2689        2689   34.2857  -119.1862  0.199776
2690        2690   34.2872  -119.1750  0.513483

[2691 rows x 4 columns]

In [158]:
ndvi_results2007 = pd.read_csv('/Users/rohan/ndvi_results2007.csv')
ndvi_results2007

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.217757
1              1   34.4592  -118.8596  0.415397
2              2   34.4609  -118.8706  0.206314
3              3   34.3317  -119.0296  0.466833
4              4   34.3298  -119.0179  0.156980
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.255601
2687        2687   34.3045  -119.0845  0.206396
2688        2688   34.3039  -119.0913  0.264975
2689        2689   34.2857  -119.1862  0.209523
2690        2690   34.2872  -119.1750  0.495688

[2691 rows x 4 columns]

In [161]:
ndvi_results2009 = pd.read_csv('/Users/rohan/ndvi_results2009.csv')
ndvi_results2009

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.156365
1              1   34.4592  -118.8596  0.415156
2              2   34.4609  -118.8706  0.208393
3              3   34.3317  -119.0296  0.542271
4              4   34.3298  -119.0179  0.193320
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.354456
2687        2687   34.3045  -119.0845  0.270226
2688        2688   34.3039  -119.0913  0.333548
2689        2689   34.2857  -119.1862  0.234534
2690        2690   34.2872  -119.1750  0.522824

[2691 rows x 4 columns]

In [162]:
ndvi_results2010 = pd.read_csv('/Users/rohan/ndvi_results2010.csv')
ndvi_results2010

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.175897
1              1   34.4592  -118.8596  0.514810
2              2   34.4609  -118.8706  0.202637
3              3   34.3317  -119.0296  0.595262
4              4   34.3298  -119.0179  0.198579
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.388149
2687        2687   34.3045  -119.0845  0.251372
2688        2688   34.3039  -119.0913  0.351903
2689        2689   34.2857  -119.1862  0.238830
2690        2690   34.2872  -119.1750  0.489521

[2691 rows x 4 columns]

In [163]:
ndvi_results2011 = pd.read_csv('/Users/rohan/ndvi_results2011.csv')
ndvi_results2011

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.189403
1              1   34.4592  -118.8596  0.541897
2              2   34.4609  -118.8706  0.224645
3              3   34.3317  -119.0296  0.520533
4              4   34.3298  -119.0179  0.217550
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.352871
2687        2687   34.3045  -119.0845  0.291879
2688        2688   34.3039  -119.0913  0.389155
2689        2689   34.2857  -119.1862  0.237687
2690        2690   34.2872  -119.1750  0.503036

[2691 rows x 4 columns]

In [165]:
ndvi_results2013 = pd.read_csv('/Users/rohan/ndvi_results2013.csv')
ndvi_results2013

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.322997
1              1   34.4592  -118.8596  0.451160
2              2   34.4609  -118.8706  0.241785
3              3   34.3317  -119.0296  0.581933
4              4   34.3298  -119.0179  0.176687
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.261303
2687        2687   34.3045  -119.0845  0.219594
2688        2688   34.3039  -119.0913  0.289662
2689        2689   34.2857  -119.1862  0.266825
2690        2690   34.2872  -119.1750  0.525106

[2691 rows x 4 columns]

In [166]:
ndvi_results2014 = pd.read_csv('/Users/rohan/ndvi_results2014.csv')
ndvi_results2014

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.157157
1              1   34.4592  -118.8596  0.438695
2              2   34.4609  -118.8706  0.237172
3              3   34.3317  -119.0296  0.652562
4              4   34.3298  -119.0179  0.179003
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.295810
2687        2687   34.3045  -119.0845  0.250739
2688        2688   34.3039  -119.0913  0.288442
2689        2689   34.2857  -119.1862  0.251938
2690        2690   34.2872  -119.1750  0.532252

[2691 rows x 4 columns]

In [167]:
ndvi_results2015 = pd.read_csv('/Users/rohan/ndvi_results2015.csv')
ndvi_results2015

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.164241
1              1   34.4592  -118.8596  0.465233
2              2   34.4609  -118.8706  0.194229
3              3   34.3317  -119.0296  0.680648
4              4   34.3298  -119.0179  0.185394
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.307121
2687        2687   34.3045  -119.0845  0.220316
2688        2688   34.3039  -119.0913  0.256296
2689        2689   34.2857  -119.1862  0.228474
2690        2690   34.2872  -119.1750  0.567150

[2691 rows x 4 columns]

In [168]:
ndvi_results2016 = pd.read_csv('/Users/rohan/ndvi_results2016.csv')
ndvi_results2016

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.165583
1              1   34.4592  -118.8596  0.413342
2              2   34.4609  -118.8706  0.260472
3              3   34.3317  -119.0296  0.611448
4              4   34.3298  -119.0179  0.176777
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.364472
2687        2687   34.3045  -119.0845  0.238655
2688        2688   34.3039  -119.0913  0.285045
2689        2689   34.2857  -119.1862  0.233806
2690        2690   34.2872  -119.1750  0.559753

[2691 rows x 4 columns]

In [169]:
ndvi_results2017 = pd.read_csv('/Users/rohan/ndvi_results2017.csv')
ndvi_results2017

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.122865
1              1   34.4592  -118.8596  0.455834
2              2   34.4609  -118.8706  0.206686
3              3   34.3317  -119.0296  0.640159
4              4   34.3298  -119.0179  0.192174
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.415602
2687        2687   34.3045  -119.0845  0.290165
2688        2688   34.3039  -119.0913  0.312699
2689        2689   34.2857  -119.1862  0.254468
2690        2690   34.2872  -119.1750  0.559743

[2691 rows x 4 columns]

In [170]:
ndvi_results2018 = pd.read_csv('/Users/rohan/ndvi_results2018.csv')
ndvi_results2018

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.122615
1              1   34.4592  -118.8596  0.516385
2              2   34.4609  -118.8706  0.239091
3              3   34.3317  -119.0296  0.535076
4              4   34.3298  -119.0179  0.177058
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.345153
2687        2687   34.3045  -119.0845  0.293229
2688        2688   34.3039  -119.0913  0.275955
2689        2689   34.2857  -119.1862  0.261212
2690        2690   34.2872  -119.1750  0.602640

[2691 rows x 4 columns]

In [171]:
ndvi_results2019 = pd.read_csv('/Users/rohan/ndvi_results2019.csv')
ndvi_results2019

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.113362
1              1   34.4592  -118.8596  0.562387
2              2   34.4609  -118.8706  0.229873
3              3   34.3317  -119.0296  0.596800
4              4   34.3298  -119.0179  0.227133
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.375557
2687        2687   34.3045  -119.0845  0.279957
2688        2688   34.3039  -119.0913  0.305564
2689        2689   34.2857  -119.1862  0.276776
2690        2690   34.2872  -119.1750  0.579781

[2691 rows x 4 columns]

In [172]:
ndvi_results2020 = pd.read_csv('/Users/rohan/ndvi_results2020.csv')
ndvi_results2020

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.188768
1              1   34.4592  -118.8596  0.535325
2              2   34.4609  -118.8706  0.225967
3              3   34.3317  -119.0296  0.453410
4              4   34.3298  -119.0179  0.230021
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.269576
2687        2687   34.3045  -119.0845  0.237036
2688        2688   34.3039  -119.0913  0.296960
2689        2689   34.2857  -119.1862  0.261154
2690        2690   34.2872  -119.1750  0.578496

[2691 rows x 4 columns]

In [173]:
ndvi_results2021 = pd.read_csv('/Users/rohan/ndvi_results2021.csv')
ndvi_results2021

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.245536
1              1   34.4592  -118.8596  0.402140
2              2   34.4609  -118.8706  0.223771
3              3   34.3317  -119.0296  0.317880
4              4   34.3298  -119.0179  0.170219
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.182947
2687        2687   34.3045  -119.0845  0.193116
2688        2688   34.3039  -119.0913  0.234675
2689        2689   34.2857  -119.1862  0.242923
2690        2690   34.2872  -119.1750  0.559918

[2691 rows x 4 columns]

In [174]:
ndvi_results2022 = pd.read_csv('/Users/rohan/ndvi_results2022.csv')
ndvi_results2022

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.057681
1              1   34.4592  -118.8596  0.202682
2              2   34.4609  -118.8706  0.112112
3              3   34.3317  -119.0296  0.133303
4              4   34.3298  -119.0179  0.116826
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.162953
2687        2687   34.3045  -119.0845  0.125251
2688        2688   34.3039  -119.0913  0.124069
2689        2689   34.2857  -119.1862  0.109967
2690        2690   34.2872  -119.1750  0.248984

[2691 rows x 4 columns]

In [175]:
ndvi_results2023 = pd.read_csv('/Users/rohan/ndvi_results2023.csv')
ndvi_results2023

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.117107
1              1   34.4592  -118.8596  0.180689
2              2   34.4609  -118.8706  0.123683
3              3   34.3317  -119.0296  0.137608
4              4   34.3298  -119.0179  0.126685
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.194529
2687        2687   34.3045  -119.0845  0.173666
2688        2688   34.3039  -119.0913  0.148173
2689        2689   34.2857  -119.1862  0.123252
2690        2690   34.2872  -119.1750  0.251813

[2691 rows x 4 columns]

In [180]:
df = pd.read_csv('/Users/rohan/ndvi_results2000v2.csv')
df

,Unnamed: 0,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI
0,2,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,6.03,295.3,50.3,D,0,0.180210
1,4,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,6.03,293.6,26.8,D,0,0.396002
2,6,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,6.03,292.1,21.7,D,0,0.155087
3,7,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,6.03,290.7,37.7,D,0,0.435763
4,9,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,6.03,294.7,20.8,D,0,0.168969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,4110,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,61.03,295.7,71.2,D,0,0.279683
2687,4112,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,61.03,294.2,80.3,D,0,0.237406
2688,4114,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,61.03,293.5,49.8,D,0,0.333590
2689,4119,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,61.03,293.7,23.0,D,2,0.169533
2690,4121,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,61.03,293.7,18.2,D,2,0.542101

In [181]:
df = df.drop(columns=['Unnamed: 0'])
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,6.03,295.3,50.3,D,0,0.180210
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,6.03,293.6,26.8,D,0,0.396002
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,6.03,292.1,21.7,D,0,0.155087
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,6.03,290.7,37.7,D,0,0.435763
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,6.03,294.7,20.8,D,0,0.168969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,61.03,295.7,71.2,D,0,0.279683
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,61.03,294.2,80.3,D,0,0.237406
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,61.03,293.5,49.8,D,0,0.333590
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,61.03,293.7,23.0,D,2,0.169533
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,61.03,293.7,18.2,D,2,0.542101

In [182]:
df.rename(columns = {'NDVI':'NDVI_2000'}, inplace=True)
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,6.03,295.3,50.3,D,0,0.180210
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,6.03,293.6,26.8,D,0,0.396002
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,6.03,292.1,21.7,D,0,0.155087
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,6.03,290.7,37.7,D,0,0.435763
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,6.03,294.7,20.8,D,0,0.168969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,61.03,295.7,71.2,D,0,0.279683
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,61.03,294.2,80.3,D,0,0.237406
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,61.03,293.5,49.8,D,0,0.333590
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,61.03,293.7,23.0,D,2,0.169533
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,61.03,293.7,18.2,D,2,0.542101

In [183]:
ndvi_results2001

      Unnamed: 0  latitude  longitude      NDVI
0              0   34.3716  -118.9757  0.198146
1              1   34.4592  -118.8596  0.484689
2              2   34.4609  -118.8706  0.212678
3              3   34.3317  -119.0296  0.346661
4              4   34.3298  -119.0179  0.198264
...          ...       ...        ...       ...
2686        2686   34.3057  -119.0683  0.308845
2687        2687   34.3045  -119.0845  0.262563
2688        2688   34.3039  -119.0913  0.356757
2689        2689   34.2857  -119.1862  0.191063
2690        2690   34.2872  -119.1750  0.502688

[2691 rows x 4 columns]

In [185]:
ndvi2001 = ndvi_results2001[['NDVI']]
ndvi2001

          NDVI
0     0.198146
1     0.484689
2     0.212678
3     0.346661
4     0.198264
...        ...
2686  0.308845
2687  0.262563
2688  0.356757
2689  0.191063
2690  0.502688

[2691 rows x 1 columns]

In [187]:
df['NDVI_2001'] = ndvi2001.values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,6.03,295.3,50.3,D,0,0.180210,0.198146
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,6.03,293.6,26.8,D,0,0.396002,0.484689
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,6.03,292.1,21.7,D,0,0.155087,0.212678
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,6.03,290.7,37.7,D,0,0.435763,0.346661
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,6.03,294.7,20.8,D,0,0.168969,0.198264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,61.03,295.7,71.2,D,0,0.279683,0.308845
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,61.03,294.2,80.3,D,0,0.237406,0.262563
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,61.03,293.5,49.8,D,0,0.333590,0.356757
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,61.03,293.7,23.0,D,2,0.169533,0.191063
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,61.03,293.7,18.2,D,2,0.542101,0.502688

In [189]:
df['NDVI_2002'] = ndvi_results2002[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,6.03,295.3,50.3,D,0,0.180210,0.198146,0.207247
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,6.03,293.6,26.8,D,0,0.396002,0.484689,0.421418
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,6.03,292.1,21.7,D,0,0.155087,0.212678,0.187728
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,6.03,290.7,37.7,D,0,0.435763,0.346661,0.433419
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,6.03,294.7,20.8,D,0,0.168969,0.198264,0.161847
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,61.03,295.7,71.2,D,0,0.279683,0.308845,0.243872
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,61.03,294.2,80.3,D,0,0.237406,0.262563,0.193867
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,61.03,293.5,49.8,D,0,0.333590,0.356757,0.252774
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,61.03,293.7,23.0,D,2,0.169533,0.191063,0.189498
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,61.03,293.7,18.2,D,2,0.542101,0.502688,0.517409

In [190]:
df['NDVI_2003'] = ndvi_results2003[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,6.03,295.3,50.3,D,0,0.180210,0.198146,0.207247,0.239830
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,6.03,293.6,26.8,D,0,0.396002,0.484689,0.421418,0.525469
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,6.03,292.1,21.7,D,0,0.155087,0.212678,0.187728,0.201397
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,6.03,290.7,37.7,D,0,0.435763,0.346661,0.433419,0.537519
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,6.03,294.7,20.8,D,0,0.168969,0.198264,0.161847,0.180771
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,61.03,295.7,71.2,D,0,0.279683,0.308845,0.243872,0.277882
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,61.03,294.2,80.3,D,0,0.237406,0.262563,0.193867,0.243622
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,61.03,293.5,49.8,D,0,0.333590,0.356757,0.252774,0.311972
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,61.03,293.7,23.0,D,2,0.169533,0.191063,0.189498,0.198719
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,61.03,293.7,18.2,D,2,0.542101,0.502688,0.517409,0.535394

In [191]:
df['NDVI_2004'] = ndvi_results2004[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,6.03,295.3,50.3,D,0,0.180210,0.198146,0.207247,0.239830,0.200820
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,6.03,293.6,26.8,D,0,0.396002,0.484689,0.421418,0.525469,0.331276
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,6.03,292.1,21.7,D,0,0.155087,0.212678,0.187728,0.201397,0.210924
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,6.03,290.7,37.7,D,0,0.435763,0.346661,0.433419,0.537519,0.477115
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,6.03,294.7,20.8,D,0,0.168969,0.198264,0.161847,0.180771,0.165291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,61.03,295.7,71.2,D,0,0.279683,0.308845,0.243872,0.277882,0.232851
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,61.03,294.2,80.3,D,0,0.237406,0.262563,0.193867,0.243622,0.248821
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,61.03,293.5,49.8,D,0,0.333590,0.356757,0.252774,0.311972,0.235585
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,61.03,293.7,23.0,D,2,0.169533,0.191063,0.189498,0.198719,0.207876
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,61.03,293.7,18.2,D,2,0.542101,0.502688,0.517409,0.535394,0.516628

In [192]:
df['NDVI_2005'] = ndvi_results2005[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,295.3,50.3,D,0,0.180210,0.198146,0.207247,0.239830,0.200820,0.055329
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,293.6,26.8,D,0,0.396002,0.484689,0.421418,0.525469,0.331276,0.504999
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,292.1,21.7,D,0,0.155087,0.212678,0.187728,0.201397,0.210924,0.259487
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,290.7,37.7,D,0,0.435763,0.346661,0.433419,0.537519,0.477115,0.532182
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,294.7,20.8,D,0,0.168969,0.198264,0.161847,0.180771,0.165291,0.187256
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,295.7,71.2,D,0,0.279683,0.308845,0.243872,0.277882,0.232851,0.334356
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,294.2,80.3,D,0,0.237406,0.262563,0.193867,0.243622,0.248821,0.275026
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,293.5,49.8,D,0,0.333590,0.356757,0.252774,0.311972,0.235585,0.295847
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,293.7,23.0,D,2,0.169533,0.191063,0.189498,0.198719,0.207876,0.200573
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,293.7,18.2,D,2,0.542101,0.502688,0.517409,0.535394,0.516628,0.497478

In [193]:
df['NDVI_2006'] = ndvi_results2006[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,50.3,D,0,0.180210,0.198146,0.207247,0.239830,0.200820,0.055329,0.092687
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,26.8,D,0,0.396002,0.484689,0.421418,0.525469,0.331276,0.504999,0.439264
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,21.7,D,0,0.155087,0.212678,0.187728,0.201397,0.210924,0.259487,0.197131
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,37.7,D,0,0.435763,0.346661,0.433419,0.537519,0.477115,0.532182,0.489130
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,20.8,D,0,0.168969,0.198264,0.161847,0.180771,0.165291,0.187256,0.156078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,71.2,D,0,0.279683,0.308845,0.243872,0.277882,0.232851,0.334356,0.285769
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,80.3,D,0,0.237406,0.262563,0.193867,0.243622,0.248821,0.275026,0.238492
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,49.8,D,0,0.333590,0.356757,0.252774,0.311972,0.235585,0.295847,0.326463
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,23.0,D,2,0.169533,0.191063,0.189498,0.198719,0.207876,0.200573,0.199776
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,18.2,D,2,0.542101,0.502688,0.517409,0.535394,0.516628,0.497478,0.513483

In [194]:
df['NDVI_2007'] = ndvi_results2007[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,D,0,0.180210,0.198146,0.207247,0.239830,0.200820,0.055329,0.092687,0.217757
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,D,0,0.396002,0.484689,0.421418,0.525469,0.331276,0.504999,0.439264,0.415397
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,D,0,0.155087,0.212678,0.187728,0.201397,0.210924,0.259487,0.197131,0.206314
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,D,0,0.435763,0.346661,0.433419,0.537519,0.477115,0.532182,0.489130,0.466833
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,D,0,0.168969,0.198264,0.161847,0.180771,0.165291,0.187256,0.156078,0.156980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,D,0,0.279683,0.308845,0.243872,0.277882,0.232851,0.334356,0.285769,0.255601
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,D,0,0.237406,0.262563,0.193867,0.243622,0.248821,0.275026,0.238492,0.206396
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,D,0,0.333590,0.356757,0.252774,0.311972,0.235585,0.295847,0.326463,0.264975
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,D,2,0.169533,0.191063,0.189498,0.198719,0.207876,0.200573,0.199776,0.209523
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,D,2,0.542101,0.502688,0.517409,0.535394,0.516628,0.497478,0.513483,0.495688

In [198]:
ndvi_results2008v2 = pd.read_csv('/Users/rohan/ndvi_results2008v2.csv')
df['NDVI_2008'] = ndvi_results2008v2[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,0,0.180210,0.198146,0.207247,0.239830,0.200820,0.055329,0.092687,0.217757,0.121215
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,0,0.396002,0.484689,0.421418,0.525469,0.331276,0.504999,0.439264,0.415397,0.312025
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,0,0.155087,0.212678,0.187728,0.201397,0.210924,0.259487,0.197131,0.206314,0.260396
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,0,0.435763,0.346661,0.433419,0.537519,0.477115,0.532182,0.489130,0.466833,0.568988
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,0,0.168969,0.198264,0.161847,0.180771,0.165291,0.187256,0.156078,0.156980,0.191201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,0,0.279683,0.308845,0.243872,0.277882,0.232851,0.334356,0.285769,0.255601,0.317380
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,0,0.237406,0.262563,0.193867,0.243622,0.248821,0.275026,0.238492,0.206396,0.277364
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,0,0.333590,0.356757,0.252774,0.311972,0.235585,0.295847,0.326463,0.264975,0.330906
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,2,0.169533,0.191063,0.189498,0.198719,0.207876,0.200573,0.199776,0.209523,0.222448
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,2,0.542101,0.502688,0.517409,0.535394,0.516628,0.497478,0.513483,0.495688,0.495911

In [199]:
df['NDVI_2009'] = ndvi_results2009[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,0.180210,0.198146,0.207247,0.239830,0.200820,0.055329,0.092687,0.217757,0.121215,0.156365
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,0.396002,0.484689,0.421418,0.525469,0.331276,0.504999,0.439264,0.415397,0.312025,0.415156
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,0.155087,0.212678,0.187728,0.201397,0.210924,0.259487,0.197131,0.206314,0.260396,0.208393
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,0.435763,0.346661,0.433419,0.537519,0.477115,0.532182,0.489130,0.466833,0.568988,0.542271
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,0.168969,0.198264,0.161847,0.180771,0.165291,0.187256,0.156078,0.156980,0.191201,0.193320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,0.279683,0.308845,0.243872,0.277882,0.232851,0.334356,0.285769,0.255601,0.317380,0.354456
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,0.237406,0.262563,0.193867,0.243622,0.248821,0.275026,0.238492,0.206396,0.277364,0.270226
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,0.333590,0.356757,0.252774,0.311972,0.235585,0.295847,0.326463,0.264975,0.330906,0.333548
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,0.169533,0.191063,0.189498,0.198719,0.207876,0.200573,0.199776,0.209523,0.222448,0.234534
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,0.542101,0.502688,0.517409,0.535394,0.516628,0.497478,0.513483,0.495688,0.495911,0.522824

In [200]:
df['NDVI_2010'] = ndvi_results2010[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,0.198146,0.207247,0.239830,0.200820,0.055329,0.092687,0.217757,0.121215,0.156365,0.175897
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,0.484689,0.421418,0.525469,0.331276,0.504999,0.439264,0.415397,0.312025,0.415156,0.514810
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,0.212678,0.187728,0.201397,0.210924,0.259487,0.197131,0.206314,0.260396,0.208393,0.202637
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,0.346661,0.433419,0.537519,0.477115,0.532182,0.489130,0.466833,0.568988,0.542271,0.595262
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,0.198264,0.161847,0.180771,0.165291,0.187256,0.156078,0.156980,0.191201,0.193320,0.198579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,0.308845,0.243872,0.277882,0.232851,0.334356,0.285769,0.255601,0.317380,0.354456,0.388149
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,0.262563,0.193867,0.243622,0.248821,0.275026,0.238492,0.206396,0.277364,0.270226,0.251372
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,0.356757,0.252774,0.311972,0.235585,0.295847,0.326463,0.264975,0.330906,0.333548,0.351903
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,0.191063,0.189498,0.198719,0.207876,0.200573,0.199776,0.209523,0.222448,0.234534,0.238830
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,0.502688,0.517409,0.535394,0.516628,0.497478,0.513483,0.495688,0.495911,0.522824,0.489521

In [201]:
df['NDVI_2011'] = ndvi_results2011[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,0.207247,0.239830,0.200820,0.055329,0.092687,0.217757,0.121215,0.156365,0.175897,0.189403
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,0.421418,0.525469,0.331276,0.504999,0.439264,0.415397,0.312025,0.415156,0.514810,0.541897
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,0.187728,0.201397,0.210924,0.259487,0.197131,0.206314,0.260396,0.208393,0.202637,0.224645
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,0.433419,0.537519,0.477115,0.532182,0.489130,0.466833,0.568988,0.542271,0.595262,0.520533
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,0.161847,0.180771,0.165291,0.187256,0.156078,0.156980,0.191201,0.193320,0.198579,0.217550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,0.243872,0.277882,0.232851,0.334356,0.285769,0.255601,0.317380,0.354456,0.388149,0.352871
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,0.193867,0.243622,0.248821,0.275026,0.238492,0.206396,0.277364,0.270226,0.251372,0.291879
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,0.252774,0.311972,0.235585,0.295847,0.326463,0.264975,0.330906,0.333548,0.351903,0.389155
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,0.189498,0.198719,0.207876,0.200573,0.199776,0.209523,0.222448,0.234534,0.238830,0.237687
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,0.517409,0.535394,0.516628,0.497478,0.513483,0.495688,0.495911,0.522824,0.489521,0.503036

In [203]:
df['NDVI_2013'] = ndvi_results2013[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,0.239830,0.200820,0.055329,0.092687,0.217757,0.121215,0.156365,0.175897,0.189403,0.322997
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,0.525469,0.331276,0.504999,0.439264,0.415397,0.312025,0.415156,0.514810,0.541897,0.451160
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,0.201397,0.210924,0.259487,0.197131,0.206314,0.260396,0.208393,0.202637,0.224645,0.241785
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,0.537519,0.477115,0.532182,0.489130,0.466833,0.568988,0.542271,0.595262,0.520533,0.581933
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,0.180771,0.165291,0.187256,0.156078,0.156980,0.191201,0.193320,0.198579,0.217550,0.176687
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,0.277882,0.232851,0.334356,0.285769,0.255601,0.317380,0.354456,0.388149,0.352871,0.261303
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,0.243622,0.248821,0.275026,0.238492,0.206396,0.277364,0.270226,0.251372,0.291879,0.219594
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,0.311972,0.235585,0.295847,0.326463,0.264975,0.330906,0.333548,0.351903,0.389155,0.289662
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,0.198719,0.207876,0.200573,0.199776,0.209523,0.222448,0.234534,0.238830,0.237687,0.266825
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,0.535394,0.516628,0.497478,0.513483,0.495688,0.495911,0.522824,0.489521,0.503036,0.525106

In [204]:
df['NDVI_2014'] = ndvi_results2014[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,0.200820,0.055329,0.092687,0.217757,0.121215,0.156365,0.175897,0.189403,0.322997,0.157157
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,0.331276,0.504999,0.439264,0.415397,0.312025,0.415156,0.514810,0.541897,0.451160,0.438695
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,0.210924,0.259487,0.197131,0.206314,0.260396,0.208393,0.202637,0.224645,0.241785,0.237172
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,0.477115,0.532182,0.489130,0.466833,0.568988,0.542271,0.595262,0.520533,0.581933,0.652562
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,0.165291,0.187256,0.156078,0.156980,0.191201,0.193320,0.198579,0.217550,0.176687,0.179003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,0.232851,0.334356,0.285769,0.255601,0.317380,0.354456,0.388149,0.352871,0.261303,0.295810
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,0.248821,0.275026,0.238492,0.206396,0.277364,0.270226,0.251372,0.291879,0.219594,0.250739
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,0.235585,0.295847,0.326463,0.264975,0.330906,0.333548,0.351903,0.389155,0.289662,0.288442
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,0.207876,0.200573,0.199776,0.209523,0.222448,0.234534,0.238830,0.237687,0.266825,0.251938
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,0.516628,0.497478,0.513483,0.495688,0.495911,0.522824,0.489521,0.503036,0.525106,0.532252

In [205]:
df['NDVI_2015'] = ndvi_results2015[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,0.055329,0.092687,0.217757,0.121215,0.156365,0.175897,0.189403,0.322997,0.157157,0.164241
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,0.504999,0.439264,0.415397,0.312025,0.415156,0.514810,0.541897,0.451160,0.438695,0.465233
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,0.259487,0.197131,0.206314,0.260396,0.208393,0.202637,0.224645,0.241785,0.237172,0.194229
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,0.532182,0.489130,0.466833,0.568988,0.542271,0.595262,0.520533,0.581933,0.652562,0.680648
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,0.187256,0.156078,0.156980,0.191201,0.193320,0.198579,0.217550,0.176687,0.179003,0.185394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,0.334356,0.285769,0.255601,0.317380,0.354456,0.388149,0.352871,0.261303,0.295810,0.307121
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,0.275026,0.238492,0.206396,0.277364,0.270226,0.251372,0.291879,0.219594,0.250739,0.220316
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,0.295847,0.326463,0.264975,0.330906,0.333548,0.351903,0.389155,0.289662,0.288442,0.256296
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,0.200573,0.199776,0.209523,0.222448,0.234534,0.238830,0.237687,0.266825,0.251938,0.228474
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,0.497478,0.513483,0.495688,0.495911,0.522824,0.489521,0.503036,0.525106,0.532252,0.567150

In [206]:
df['NDVI_2016'] = ndvi_results2016[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,0.092687,0.217757,0.121215,0.156365,0.175897,0.189403,0.322997,0.157157,0.164241,0.165583
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,0.439264,0.415397,0.312025,0.415156,0.514810,0.541897,0.451160,0.438695,0.465233,0.413342
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,0.197131,0.206314,0.260396,0.208393,0.202637,0.224645,0.241785,0.237172,0.194229,0.260472
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,0.489130,0.466833,0.568988,0.542271,0.595262,0.520533,0.581933,0.652562,0.680648,0.611448
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,0.156078,0.156980,0.191201,0.193320,0.198579,0.217550,0.176687,0.179003,0.185394,0.176777
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,0.285769,0.255601,0.317380,0.354456,0.388149,0.352871,0.261303,0.295810,0.307121,0.364472
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,0.238492,0.206396,0.277364,0.270226,0.251372,0.291879,0.219594,0.250739,0.220316,0.238655
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,0.326463,0.264975,0.330906,0.333548,0.351903,0.389155,0.289662,0.288442,0.256296,0.285045
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,0.199776,0.209523,0.222448,0.234534,0.238830,0.237687,0.266825,0.251938,0.228474,0.233806
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,0.513483,0.495688,0.495911,0.522824,0.489521,0.503036,0.525106,0.532252,0.567150,0.559753

In [207]:
df['NDVI_2017'] = ndvi_results2017[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,0.217757,0.121215,0.156365,0.175897,0.189403,0.322997,0.157157,0.164241,0.165583,0.122865
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,0.415397,0.312025,0.415156,0.514810,0.541897,0.451160,0.438695,0.465233,0.413342,0.455834
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,0.206314,0.260396,0.208393,0.202637,0.224645,0.241785,0.237172,0.194229,0.260472,0.206686
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,0.466833,0.568988,0.542271,0.595262,0.520533,0.581933,0.652562,0.680648,0.611448,0.640159
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,0.156980,0.191201,0.193320,0.198579,0.217550,0.176687,0.179003,0.185394,0.176777,0.192174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,0.255601,0.317380,0.354456,0.388149,0.352871,0.261303,0.295810,0.307121,0.364472,0.415602
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,0.206396,0.277364,0.270226,0.251372,0.291879,0.219594,0.250739,0.220316,0.238655,0.290165
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,0.264975,0.330906,0.333548,0.351903,0.389155,0.289662,0.288442,0.256296,0.285045,0.312699
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,0.209523,0.222448,0.234534,0.238830,0.237687,0.266825,0.251938,0.228474,0.233806,0.254468
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,0.495688,0.495911,0.522824,0.489521,0.503036,0.525106,0.532252,0.567150,0.559753,0.559743

In [208]:
df['NDVI_2018'] = ndvi_results2018[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,0.121215,0.156365,0.175897,0.189403,0.322997,0.157157,0.164241,0.165583,0.122865,0.122615
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,0.312025,0.415156,0.514810,0.541897,0.451160,0.438695,0.465233,0.413342,0.455834,0.516385
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,0.260396,0.208393,0.202637,0.224645,0.241785,0.237172,0.194229,0.260472,0.206686,0.239091
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,0.568988,0.542271,0.595262,0.520533,0.581933,0.652562,0.680648,0.611448,0.640159,0.535076
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,0.191201,0.193320,0.198579,0.217550,0.176687,0.179003,0.185394,0.176777,0.192174,0.177058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,0.317380,0.354456,0.388149,0.352871,0.261303,0.295810,0.307121,0.364472,0.415602,0.345153
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,0.277364,0.270226,0.251372,0.291879,0.219594,0.250739,0.220316,0.238655,0.290165,0.293229
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,0.330906,0.333548,0.351903,0.389155,0.289662,0.288442,0.256296,0.285045,0.312699,0.275955
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,0.222448,0.234534,0.238830,0.237687,0.266825,0.251938,0.228474,0.233806,0.254468,0.261212
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,0.495911,0.522824,0.489521,0.503036,0.525106,0.532252,0.567150,0.559753,0.559743,0.602640

In [209]:
df['NDVI_2019'] = ndvi_results2019[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,0.156365,0.175897,0.189403,0.322997,0.157157,0.164241,0.165583,0.122865,0.122615,0.113362
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,0.415156,0.514810,0.541897,0.451160,0.438695,0.465233,0.413342,0.455834,0.516385,0.562387
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,0.208393,0.202637,0.224645,0.241785,0.237172,0.194229,0.260472,0.206686,0.239091,0.229873
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,0.542271,0.595262,0.520533,0.581933,0.652562,0.680648,0.611448,0.640159,0.535076,0.596800
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,0.193320,0.198579,0.217550,0.176687,0.179003,0.185394,0.176777,0.192174,0.177058,0.227133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,0.354456,0.388149,0.352871,0.261303,0.295810,0.307121,0.364472,0.415602,0.345153,0.375557
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,0.270226,0.251372,0.291879,0.219594,0.250739,0.220316,0.238655,0.290165,0.293229,0.279957
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,0.333548,0.351903,0.389155,0.289662,0.288442,0.256296,0.285045,0.312699,0.275955,0.305564
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,0.234534,0.238830,0.237687,0.266825,0.251938,0.228474,0.233806,0.254468,0.261212,0.276776
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,0.522824,0.489521,0.503036,0.525106,0.532252,0.567150,0.559753,0.559743,0.602640,0.579781

In [210]:
df['NDVI_2020'] = ndvi_results2020[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,0.175897,0.189403,0.322997,0.157157,0.164241,0.165583,0.122865,0.122615,0.113362,0.188768
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,0.514810,0.541897,0.451160,0.438695,0.465233,0.413342,0.455834,0.516385,0.562387,0.535325
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,0.202637,0.224645,0.241785,0.237172,0.194229,0.260472,0.206686,0.239091,0.229873,0.225967
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,0.595262,0.520533,0.581933,0.652562,0.680648,0.611448,0.640159,0.535076,0.596800,0.453410
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,0.198579,0.217550,0.176687,0.179003,0.185394,0.176777,0.192174,0.177058,0.227133,0.230021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,0.388149,0.352871,0.261303,0.295810,0.307121,0.364472,0.415602,0.345153,0.375557,0.269576
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,0.251372,0.291879,0.219594,0.250739,0.220316,0.238655,0.290165,0.293229,0.279957,0.237036
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,0.351903,0.389155,0.289662,0.288442,0.256296,0.285045,0.312699,0.275955,0.305564,0.296960
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,0.238830,0.237687,0.266825,0.251938,0.228474,0.233806,0.254468,0.261212,0.276776,0.261154
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,0.489521,0.503036,0.525106,0.532252,0.567150,0.559753,0.559743,0.602640,0.579781,0.578496

In [211]:
df['NDVI_2021'] = ndvi_results2021[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,0.189403,0.322997,0.157157,0.164241,0.165583,0.122865,0.122615,0.113362,0.188768,0.245536
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,0.541897,0.451160,0.438695,0.465233,0.413342,0.455834,0.516385,0.562387,0.535325,0.402140
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,0.224645,0.241785,0.237172,0.194229,0.260472,0.206686,0.239091,0.229873,0.225967,0.223771
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,0.520533,0.581933,0.652562,0.680648,0.611448,0.640159,0.535076,0.596800,0.453410,0.317880
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,0.217550,0.176687,0.179003,0.185394,0.176777,0.192174,0.177058,0.227133,0.230021,0.170219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,0.352871,0.261303,0.295810,0.307121,0.364472,0.415602,0.345153,0.375557,0.269576,0.182947
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,0.291879,0.219594,0.250739,0.220316,0.238655,0.290165,0.293229,0.279957,0.237036,0.193116
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,0.389155,0.289662,0.288442,0.256296,0.285045,0.312699,0.275955,0.305564,0.296960,0.234675
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,0.237687,0.266825,0.251938,0.228474,0.233806,0.254468,0.261212,0.276776,0.261154,0.242923
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,0.503036,0.525106,0.532252,0.567150,0.559753,0.559743,0.602640,0.579781,0.578496,0.559918

In [212]:
df['NDVI_2022'] = ndvi_results2022[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021,NDVI_2022
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,0.322997,0.157157,0.164241,0.165583,0.122865,0.122615,0.113362,0.188768,0.245536,0.057681
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,0.451160,0.438695,0.465233,0.413342,0.455834,0.516385,0.562387,0.535325,0.402140,0.202682
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,0.241785,0.237172,0.194229,0.260472,0.206686,0.239091,0.229873,0.225967,0.223771,0.112112
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,0.581933,0.652562,0.680648,0.611448,0.640159,0.535076,0.596800,0.453410,0.317880,0.133303
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,0.176687,0.179003,0.185394,0.176777,0.192174,0.177058,0.227133,0.230021,0.170219,0.116826
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,0.261303,0.295810,0.307121,0.364472,0.415602,0.345153,0.375557,0.269576,0.182947,0.162953
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,0.219594,0.250739,0.220316,0.238655,0.290165,0.293229,0.279957,0.237036,0.193116,0.125251
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,0.289662,0.288442,0.256296,0.285045,0.312699,0.275955,0.305564,0.296960,0.234675,0.124069
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,0.266825,0.251938,0.228474,0.233806,0.254468,0.261212,0.276776,0.261154,0.242923,0.109967
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,0.525106,0.532252,0.567150,0.559753,0.559743,0.602640,0.579781,0.578496,0.559918,0.248984

In [213]:
df['NDVI_2023'] = ndvi_results2023[['NDVI']].values
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,...,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021,NDVI_2022,NDVI_2023
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,...,0.157157,0.164241,0.165583,0.122865,0.122615,0.113362,0.188768,0.245536,0.057681,0.117107
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,...,0.438695,0.465233,0.413342,0.455834,0.516385,0.562387,0.535325,0.402140,0.202682,0.180689
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,...,0.237172,0.194229,0.260472,0.206686,0.239091,0.229873,0.225967,0.223771,0.112112,0.123683
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,...,0.652562,0.680648,0.611448,0.640159,0.535076,0.596800,0.453410,0.317880,0.133303,0.137608
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,...,0.179003,0.185394,0.176777,0.192174,0.177058,0.227133,0.230021,0.170219,0.116826,0.126685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,...,0.295810,0.307121,0.364472,0.415602,0.345153,0.375557,0.269576,0.182947,0.162953,0.194529
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,...,0.250739,0.220316,0.238655,0.290165,0.293229,0.279957,0.237036,0.193116,0.125251,0.173666
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,...,0.288442,0.256296,0.285045,0.312699,0.275955,0.305564,0.296960,0.234675,0.124069,0.148173
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,...,0.251938,0.228474,0.233806,0.254468,0.261212,0.276776,0.261154,0.242923,0.109967,0.123252
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,...,0.532252,0.567150,0.559753,0.559743,0.602640,0.579781,0.578496,0.559918,0.248984,0.251813

In [215]:
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021,NDVI_2022,NDVI_2023
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,MODIS,80,6.03,295.3,50.3,D,0,0.180210,0.198146,0.207247,0.239830,0.200820,0.055329,0.092687,0.217757,0.121215,0.156365,0.175897,0.189403,0.322997,0.157157,0.164241,0.165583,0.122865,0.122615,0.113362,0.188768,0.245536,0.057681,0.117107
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,6.03,293.6,26.8,D,0,0.396002,0.484689,0.421418,0.525469,0.331276,0.504999,0.439264,0.415397,0.312025,0.415156,0.514810,0.541897,0.451160,0.438695,0.465233,0.413342,0.455834,0.516385,0.562387,0.535325,0.402140,0.202682,0.180689
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,6.03,292.1,21.7,D,0,0.155087,0.212678,0.187728,0.201397,0.210924,0.259487,0.197131,0.206314,0.260396,0.208393,0.202637,0.224645,0.241785,0.237172,0.194229,0.260472,0.206686,0.239091,0.229873,0.225967,0.223771,0.112112,0.123683
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,6.03,290.7,37.7,D,0,0.435763,0.346661,0.433419,0.537519,0.477115,0.532182,0.489130,0.466833,0.568988,0.542271,0.595262,0.520533,0.581933,0.652562,0.680648,0.611448,0.640159,0.535076,0.596800,0.453410,0.317880,0.133303,0.137608
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,6.03,294.7,20.8,D,0,0.168969,0.198264,0.161847,0.180771,0.165291,0.187256,0.156078,0.156980,0.191201,0.193320,0.198579,0.217550,0.176687,0.179003,0.185394,0.176777,0.192174,0.177058,0.227133,0.230021,0.170219,0.116826,0.126685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,MODIS,84,61.03,295.7,71.2,D,0,0.279683,0.308845,0.243872,0.277882,0.232851,0.334356,0.285769,0.255601,0.317380,0.354456,0.388149,0.352871,0.261303,0.295810,0.307121,0.364472,0.415602,0.345153,0.375557,0.269576,0.182947,0.162953,0.194529
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,85,61.03,294.2,80.3,D,0,0.237406,0.262563,0.193867,0.243622,0.248821,0.275026,0.238492,0.206396,0.277364,0.270226,0.251372,0.291879,0.219594,0.250739,0.220316,0.238655,0.290165,0.293229,0.279957,0.237036,0.193116,0.125251,0.173666
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,61.03,293.5,49.8,D,0,0.333590,0.356757,0.252774,0.311972,0.235585,0.295847,0.326463,0.264975,0.330906,0.333548,0.351903,0.389155,0.289662,0.288442,0.256296,0.285045,0.312699,0.275955,0.305564,0.296960,0.234675,0.124069,0.148173
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,61.03,293.7,23.0,D,2,0.169533,0.191063,0.189498,0.198719,0.207876,0.200573,0.199776,0.209523,0.222448,0.234534,0.238830,0.237687,0.266825,0.251938,0.228474,0.233806,0.254468,0.261212,0.276776,0.261154,0.242923,0.109967,0.123252
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,61.03,293.7,18.2,D,2,0.542101,0.502688,0.517409,0.535394,0.516628,0.497478,0.513483,0.495688,0.495911,0.522824,0.489521,0.503036,0.525106,0.532252,0.567150,0.559753,0.559743,0.602640,0.579781,0.578496,0.559918,0.248984,0.251813

In [216]:
veryhot = df[df['frp']>=1000]
veryhot

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021,NDVI_2022,NDVI_2023
133,34.3543,-118.8883,418.7,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,308.2,1457.0,N,0,0.205033,0.250586,0.197790,0.244488,0.238987,0.318234,0.254420,0.227132,0.266338,0.245905,0.277502,0.296700,0.198451,0.297986,0.229551,0.257074,0.325387,0.259094,0.304859,0.250000,0.196513,0.144330,0.193611
155,34.3724,-118.8334,453.3,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,322.4,2905.3,N,0,0.323111,0.379704,0.292652,0.389704,0.246654,0.421347,0.289786,0.272520,0.359585,0.344932,0.378654,0.348636,0.278418,0.275621,0.289117,0.288503,0.370304,0.282390,0.452506,0.368712,0.257016,0.133836,0.157934
158,34.3864,-118.8320,406.2,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,301.5,1119.1,N,0,0.055565,0.064852,0.068566,0.065594,0.071419,0.062743,0.081525,0.076616,0.084963,0.106344,0.123309,0.117212,0.123523,0.123177,0.135372,0.148057,0.139724,0.134325,0.156584,0.163890,0.146157,0.083138,0.053488
159,34.3788,-118.8383,466.1,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,323.7,3635.3,N,0,0.296198,0.329498,0.252348,0.306101,0.278212,0.360125,0.303514,0.224522,0.305773,0.327227,0.312932,0.359615,0.291681,0.292561,0.278466,0.272185,0.329941,0.288067,0.381150,0.351611,0.267755,0.129807,0.193051
163,34.3754,-118.8731,396.8,3.0,1.7,2003-10-26,911,Aqua,MODIS,100,6.03,303.0,1162.5,N,0,0.357952,0.374990,0.311193,0.341289,0.200089,0.381710,0.265243,0.171978,0.265032,0.254344,0.224846,0.288669,0.241493,0.311626,0.314299,0.260826,0.348485,0.284811,0.332317,0.248070,0.191462,0.182179,0.200796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2580,34.1044,-118.9523,500.0,1.0,1.0,2018-11-11,1846,Terra,MODIS,100,6.03,364.2,1605.6,D,0,0.210893,0.223888,0.191936,0.213572,0.250659,0.236750,0.241755,0.231932,0.233287,0.272271,0.274828,0.243836,0.225015,0.229403,0.219188,0.245130,0.253069,0.273316,0.265306,0.280722,0.234839,0.127381,0.117979
2581,34.1060,-118.9631,500.0,1.0,1.0,2018-11-11,1846,Terra,MODIS,100,6.03,349.5,1608.1,D,0,0.410124,0.428370,0.351566,0.443056,0.420290,0.501320,0.483057,0.340881,0.453694,0.465386,0.466112,0.536215,0.144890,0.227243,0.249100,0.275785,0.311176,0.325859,0.268405,0.322532,0.231059,0.134670,0.149597
2584,34.1133,-118.9504,474.0,1.0,1.0,2018-11-11,1846,Terra,MODIS,100,6.03,348.9,1074.0,D,0,0.321392,0.328322,0.268108,0.333911,0.321885,0.369261,0.351715,0.300660,0.314517,0.333978,0.311927,0.345255,0.230589,0.221825,0.235845,0.243555,0.276057,0.267129,0.174069,0.244949,0.176860,0.165036,0.182294
2628,34.3331,-119.0557,452.8,2.0,1.4,2019-11-01,535,Terra,MODIS,100,6.03,315.3,2075.5,N,2,0.314073,0.329715,0.290306,0.352414,0.207612,0.252484,0.299279,0.261648,0.353380,0.342659,0.365764,0.415318,0.336727,0.348948,0.336957,0.348091,0.376414,0.356120,0.380961,0.296684,0.253485,0.149244,0.199644
2630,34.3376,-119.0338,419.4,2.0,1.4,2019-11-01,535,Terra,MODIS,100,6.03,304.4,1081.1,N,2,0.274441,0.296926,0.227579,0.253099,0.225858,0.266113,0.267692,0.238946,0.289067,0.307552,0.305125,0.321443,0.286508,0.315388,0.325621,0.315827,0.365566,0.323117,0.385392,0.279328,0.233177,0.141860,0.186304

In [218]:
veryhot2003 = veryhot[veryhot['acq_date'].str[:4] == '2003']
veryhot2003

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021,NDVI_2022,NDVI_2023
133,34.3543,-118.8883,418.7,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,308.2,1457.0,N,0,0.205033,0.250586,0.197790,0.244488,0.238987,0.318234,0.254420,0.227132,0.266338,0.245905,0.277502,0.296700,0.198451,0.297986,0.229551,0.257074,0.325387,0.259094,0.304859,0.250000,0.196513,0.144330,0.193611
155,34.3724,-118.8334,453.3,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,322.4,2905.3,N,0,0.323111,0.379704,0.292652,0.389704,0.246654,0.421347,0.289786,0.272520,0.359585,0.344932,0.378654,0.348636,0.278418,0.275621,0.289117,0.288503,0.370304,0.282390,0.452506,0.368712,0.257016,0.133836,0.157934
158,34.3864,-118.8320,406.2,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,301.5,1119.1,N,0,0.055565,0.064852,0.068566,0.065594,0.071419,0.062743,0.081525,0.076616,0.084963,0.106344,0.123309,0.117212,0.123523,0.123177,0.135372,0.148057,0.139724,0.134325,0.156584,0.163890,0.146157,0.083138,0.053488
159,34.3788,-118.8383,466.1,2.5,1.5,2003-10-26,636,Terra,MODIS,100,6.03,323.7,3635.3,N,0,0.296198,0.329498,0.252348,0.306101,0.278212,0.360125,0.303514,0.224522,0.305773,0.327227,0.312932,0.359615,0.291681,0.292561,0.278466,0.272185,0.329941,0.288067,0.381150,0.351611,0.267755,0.129807,0.193051
163,34.3754,-118.8731,396.8,3.0,1.7,2003-10-26,911,Aqua,MODIS,100,6.03,303.0,1162.5,N,0,0.357952,0.374990,0.311193,0.341289,0.200089,0.381710,0.265243,0.171978,0.265032,0.254344,0.224846,0.288669,0.241493,0.311626,0.314299,0.260826,0.348485,0.284811,0.332317,0.248070,0.191462,0.182179,0.200796
245,34.4893,-118.8444,397.5,4.7,2.0,2003-10-26,2013,Aqua,MODIS,100,6.03,307.5,2167.6,D,0,0.403586,0.441520,0.337685,0.457836,0.299413,0.427353,0.404670,0.312666,0.381215,0.436506,0.478444,0.461306,0.357921,0.442361,0.425356,0.421694,0.471503,0.479368,0.534483,0.545338,0.417787,0.215377,0.197446
246,34.5005,-118.8091,393.9,4.6,2.0,2003-10-26,2013,Aqua,MODIS,100,6.03,315.1,1961.4,D,0,0.305231,0.339684,0.241105,0.338149,0.201453,0.299857,0.276338,0.242484,0.254463,0.297245,0.335587,0.351486,0.280482,0.325718,0.301429,0.316165,0.343915,0.346495,0.392114,0.382871,0.347368,0.179336,0.182737
249,34.4830,-118.7947,374.2,4.6,2.0,2003-10-26,2013,Aqua,MODIS,75,6.03,309.5,1154.8,D,0,0.482126,0.496114,0.358141,0.449623,0.314188,0.416939,0.376543,0.356862,0.386732,0.415534,0.465927,0.429272,0.443686,0.483630,0.519124,0.502069,0.470783,0.512839,0.603822,0.530746,0.453947,0.242317,0.235716
252,34.4829,-118.7974,378.1,4.6,2.0,2003-10-26,2013,Aqua,MODIS,87,6.03,309.3,1289.0,D,0,0.274599,0.356206,0.245927,0.263578,0.244958,0.357998,0.263040,0.217542,0.266405,0.301304,0.298450,0.283489,0.235080,0.261806,0.216927,0.242357,0.258977,0.266680,0.364895,0.283701,0.267642,0.189644,0.182932
253,34.5007,-118.8007,399.5,4.6,2.0,2003-10-26,2013,Aqua,MODIS,94,6.03,312.8,2248.5,D,0,0.422073,0.481379,0.315590,0.451711,0.220135,0.454455,0.405385,0.337210,0.351592,0.382037,0.449811,0.510522,0.386842,0.431147,0.410555,0.396744,0.485528,0.456810,0.563751,0.516196,0.422629,0.201007,0.209050
254,34.4504,-118.8493,396.0,4.1,1.9,2003-10-26,2151,Aqua,MODIS,100,6.03,305.1,1688.3,D,0,0.674828,0.683797,0.654298,0.669832,0.308058,0.475571,0.429113,0.479428,0.399155,0.450743,0.561834,0.572546,0.578221,0.580861,0.603791,0.532942,0.646973,0.638680,0.712469,0.697995,0.577295,0.273724,0.280147
255,34.4527,-118.8046,406.6,4.1,1.9,2003-10-26,2151,Aqua,MODIS,94,6.03,302.8,2197.5,D,0,0.396920,0.435739,0.370794,0.404038,0.313817,0.447684,0.312736,0.284987,0.379223,0.304516,0.349690,0.389800,0.330514,0.323797,0.303525,0.287537,0.361621,0.332169,0.465253,0.410267,0.317028,0.181181,0.177212
257,34.4579,-118.8149,417.8,4.1,1.9,2003-10-26,2151,Aqua,MODIS,94,6.03,311.1,2823.3,D,0,0.253456,0.407182,0.350183,0.445990,0.188711,0.333803,0.286848,0.289178,0.343213,0.368421,0.439337,0.439421,0.458789,0.492896,0.511911,0.455319,0.491405,0.474560,0.588931,0.558741,0.484888,0.159838,0.082432
260,34.4748,-118.8156,422.1,4.1,1.9,2003-10-26,2151,Aqua,MODIS,94,6.03,317.3,3102.1,D,0,0.428076,0.456386,0.349759,0.433820,0.267829,0.484707,0.511025,0.330451,0.313927,0.402012,0.468655,0.481869,0.374029,0.401339,0.366460,0.366703,0.433568,0.437250,0.543985,0.506865,0.411799,0.227541,0.255502
266,34.4670,-118.8555,398.5,4.1,1.9,2003-10-26,2151,Aqua,MODIS,100,6.03,312.3,1791.5,D,0,0.194129,0.244209,0.220379,0.219126,0.231143,0.265025,0.206154,0.205484,0.225114,0.227098,0.232759,0.233901,0.221939,0.218259,0.202588,0.246296,0.222727,0.248060,0.250559,0.258092,0.224200,0.188053,0.197911
267,34.4696,-118.8052,428.1,4.1,1.9,2003-10-26,2151,Aqua,MODIS,87,6.03,315.9,3526.2,D,0,0.310924,0.406897,0.308619,0.380832,0.212949,0.326207,0.338438,0.304491,0.332139,0.372669,0.430417,0.377146,0.367188,0.415058,0.364075,0.378576,0.420305,0.425804,0.481843,0.465145,0.383430,0.156237,0.158386
343,34.4654,-118.9101,406.2,2.5,1.5,2003-10-27,1922,Terra,MODIS,100,6.03,312.6,1080.6,D,2,0.404848,0.378534,0.377706,0.429435,0.246109,0.333071,0.353396,0.320997,0.357646,0.391940,0.422702,0.457816,0.406369,0.446869,0.437026,0.447141,0.457093,0.477860,0.504117,0.499067,0.438077,0.183108,0.159823
353,34.4648,-118.9138,484.6,1.1,1.0,2003-10-27,2056,Aqua,MODIS,100,6.03,341.4,1439.9,D,2,0.334751,0.353403,0.307541,0.354344,0.266049,0.230120,0.228700,0.225386,0.254885,0.314649,0.304543,0.343315,0.315497,0.313773,0.323976,0.323359,0.304762,0.329670,0.363691,0.373524,0.319420,0.156492,0.166733
355,34.4742,-118.9153,500.1,1.1,1.0,2003-10-27,2056,Aqua,MODIS,100,6.03,400.1,1825.9,D,0,0.521127,0.505460,0.430747,0.567945,0.260564,0.478333,0.486327,0.347181,0.462483,0.486793,0.553299,0.582691,0.486467,0.567904,0.570424,0.519169,0.611247,0.616426,0.694012,0.672691,0.535339,0.235010,0.277330
356,34.4761,-118.9034,488.0,1.1,1.0,2003-10-27,2056,Aqua,MODIS,100,6.03,326.0,1519.8,D,0,0.462797,0.440901,0.353427,0.486821,0.214291,0.423147,0.424231,0.345746,0.430093,0.463343,0.505105,0.538219,0.473009,0.529182,0.530009,0.505404,0.562846,0.568033,0.597904,0.595246,0.453130,0.192836,0.196934
357,34.4668,-118.9015,480.0,1.1,1.0,2003-10-27,2056,Aqua,MODIS,100,6.03,330.8,1337.5,D,2,0.396214,0.382211,0.327960,0.411489,0.228012,0.355627,0.371371,0.315619,0.370129,0.406480,0.421607,0.475646,0.387759,0.432804,0.422082,0.418080,0.447608,0.463070,0.499464,0.504435,0.413171,0.182298,0.210849
367,34.4723,-118.9270,474.4,1.1,1.0,2003-10-27,2056,Aqua,MODIS,100,6.03,317.9,1224.3,D,0,0.543722,0.506091,0.426730,0.552800,0.290659,0.460112,0.400212,0.360129,0.447931,0.488151,0.533717,0.557974,0.499363,0.572081,0.591588,0.543099,0.601781,0.618402,0.658049,0.671040,0.506862,0.215380,0.234746
414,34.5046,-118.8849,438.5,1.5,1.2,2003-10-28,1827,Terra,MODIS,100,6.03,322.7,1040.2,D,0,0.278400,0.302217,0.223804,0.286757,0.168341,0.226677,0.203363,0.196842,0.228420,0.269681,0.264262,0.285827,0.240186,0.266706,0.249197,0.274330,0.273421,0.277569,0.289994,0.306914,0.256327,0.105239,0.116760
418,34.5059,-118.8767,477.7,1.5,1.2,2003-10-28,1827,Terra,MODIS,100,6.03,338.4,2114.3,D,0,0.300491,0.346616,0.259369,0.314845,0.167646,0.258938,0.257328,0.198103,0.261031,0.272378,0.313353,0.301587,0.234914,0.253643,0.241704,0.264067,0.290657,0.284828,0.317002,0.340810,0.259132,0.161397,0.169548
430,34.5026,-118.8664,447.0,1.5,1.2,2003-10-28,1827,Terra,MODIS,100,6.03,329.4,1226.5,D,0,0.438415,0.449204,0.390991,0.514384,0.487090,0.546625,0.562510,0.480258,0.513846,0.529165,0.582615,0.606568,0.501489,0.537550,0.532866,0.539734,0.567953,0.572202,0.624011,0.647375,0.506495,0.224682,0.227211
443,34.5169,-118.9164,434.4,2.5,1.5,2003-10-28,2139,Aqua,MODIS,100,6.03,310.0,2014.4,D,0,0.497295,0.489015,0.416393,0.527028,0.260001,0.388776,0.388837,0.342248,0.391466,0.424898,0.437867,0.427521,0.416348,0.475078,0.492250,0.469368,0.467470,0.484303,0.515543,0.523644,0.466329,0.179083,0.180796

In [255]:
veryhot2003['NDVI_2005'].mean()

0.3667378540222461

In [256]:
verycool = df[df['frp']<=50]
verycool

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021,NDVI_2022,NDVI_2023
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,MODIS,86,6.03,293.6,26.8,D,0,0.396002,0.484689,0.421418,0.525469,0.331276,0.504999,0.439264,0.415397,0.312025,0.415156,0.514810,0.541897,0.451160,0.438695,0.465233,0.413342,0.455834,0.516385,0.562387,0.535325,0.402140,0.202682,0.180689
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,MODIS,83,6.03,292.1,21.7,D,0,0.155087,0.212678,0.187728,0.201397,0.210924,0.259487,0.197131,0.206314,0.260396,0.208393,0.202637,0.224645,0.241785,0.237172,0.194229,0.260472,0.206686,0.239091,0.229873,0.225967,0.223771,0.112112,0.123683
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,MODIS,88,6.03,290.7,37.7,D,0,0.435763,0.346661,0.433419,0.537519,0.477115,0.532182,0.489130,0.466833,0.568988,0.542271,0.595262,0.520533,0.581933,0.652562,0.680648,0.611448,0.640159,0.535076,0.596800,0.453410,0.317880,0.133303,0.137608
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,MODIS,81,6.03,294.7,20.8,D,0,0.168969,0.198264,0.161847,0.180771,0.165291,0.187256,0.156078,0.156980,0.191201,0.193320,0.198579,0.217550,0.176687,0.179003,0.185394,0.176777,0.192174,0.177058,0.227133,0.230021,0.170219,0.116826,0.126685
6,34.2618,-119.0730,313.7,2.5,1.5,2001-01-22,1934,Terra,MODIS,74,6.03,289.2,42.9,D,0,0.348322,0.218262,0.194954,0.219191,0.279726,0.263491,0.223807,0.204253,0.290051,0.231292,0.316539,0.502903,0.366889,0.282562,0.395550,0.443011,0.233188,0.290997,0.202758,0.254158,0.301775,0.133126,0.143203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2682,34.3557,-119.0312,317.9,1.1,1.0,2022-02-16,1832,Terra,MODIS,78,6.03,292.6,16.1,D,2,0.192585,0.154724,0.179895,0.211563,0.228975,0.140846,0.113658,0.159030,0.176617,0.224961,0.241400,0.241679,0.464590,0.448425,0.469360,0.461417,0.514214,0.536958,0.599701,0.634581,0.587721,0.216980,0.242812
2685,34.2099,-119.1278,326.4,1.1,1.1,2023-08-31,1831,Terra,MODIS,72,61.03,305.6,15.2,D,2,0.059678,0.070314,0.059808,0.061463,0.081294,0.083138,0.060864,0.058227,0.059427,0.078410,0.070340,0.075713,0.082232,0.076925,0.068852,0.083644,0.087278,0.085386,0.087886,0.102419,0.097375,0.043828,0.043338
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,MODIS,75,61.03,293.5,49.8,D,0,0.333590,0.356757,0.252774,0.311972,0.235585,0.295847,0.326463,0.264975,0.330906,0.333548,0.351903,0.389155,0.289662,0.288442,0.256296,0.285045,0.312699,0.275955,0.305564,0.296960,0.234675,0.124069,0.148173
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,MODIS,83,61.03,293.7,23.0,D,2,0.169533,0.191063,0.189498,0.198719,0.207876,0.200573,0.199776,0.209523,0.222448,0.234534,0.238830,0.237687,0.266825,0.251938,0.228474,0.233806,0.254468,0.261212,0.276776,0.261154,0.242923,0.109967,0.123252
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,MODIS,80,61.03,293.7,18.2,D,2,0.542101,0.502688,0.517409,0.535394,0.516628,0.497478,0.513483,0.495688,0.495911,0.522824,0.489521,0.503036,0.525106,0.532252,0.567150,0.559753,0.559743,0.602640,0.579781,0.578496,0.559918,0.248984,0.251813

In [257]:
verycool2003 = verycool[verycool['acq_date'].str[:4] == '2003']
verycool2003

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021,NDVI_2022,NDVI_2023
78,34.0502,-118.8636,311.7,1.2,1.1,2003-01-07,936,Aqua,MODIS,83,6.03,290.4,15.6,N,0,0.200378,0.260166,0.310649,0.382643,0.409946,0.424909,0.374290,0.328869,0.383838,0.407747,0.461323,0.337046,0.450342,0.436491,0.512350,0.412095,0.483429,0.479649,0.305370,0.474510,0.418666,0.169049,0.209590
79,34.3295,-119.1626,317.4,1.6,1.2,2003-01-13,1828,Terra,MODIS,78,6.03,285.4,31.2,D,0,0.277311,0.322391,0.228666,0.321167,0.338462,0.333730,0.274128,0.226597,0.291995,0.291324,0.291411,0.288448,0.250645,0.262950,0.212888,0.267973,0.320308,0.275591,0.277804,0.261211,0.227847,0.141799,0.153263
80,34.3886,-118.8585,316.4,1.5,1.2,2003-01-13,1828,Terra,MODIS,77,6.03,289.1,25.8,D,0,0.080570,0.110149,0.104343,0.111931,0.114948,0.182217,0.206006,0.155307,0.171885,0.219018,0.207921,0.305082,0.261993,0.226000,0.249981,0.237625,0.240352,0.223037,0.258548,0.253612,0.215051,0.114207,0.144842
81,34.3278,-119.1461,315.8,1.6,1.2,2003-01-13,1828,Terra,MODIS,76,6.03,285.0,28.2,D,0,0.616787,0.568520,0.515136,0.536828,0.551142,0.541665,0.566544,0.496915,0.524196,0.566793,0.539146,0.229032,0.283639,0.313474,0.348714,0.409180,0.455407,0.543114,0.653359,0.683678,0.677389,0.376135,0.368637
82,34.3776,-118.8595,311.8,1.5,1.2,2003-01-13,1828,Terra,MODIS,72,6.03,289.4,18.5,D,0,0.308201,0.337711,0.277046,0.325926,0.245060,0.349297,0.268212,0.212696,0.288019,0.289982,0.261895,0.272794,0.222042,0.240573,0.202149,0.206532,0.237728,0.212958,0.261554,0.247357,0.212148,0.125276,0.168823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,34.4633,-119.2163,312.8,1.0,1.0,2003-11-25,1852,Terra,MODIS,73,6.03,287.8,12.0,D,0,0.371515,0.414149,0.382198,0.362806,0.445646,0.427430,0.440747,0.392602,0.333182,0.398370,0.427152,0.431768,0.396755,0.422282,0.424275,0.396451,0.333485,0.379263,0.411250,0.442045,0.380215,0.160579,0.151695
499,34.3729,-118.9256,315.9,1.6,1.3,2003-12-01,2127,Aqua,MODIS,72,6.03,294.5,22.1,D,0,0.585647,0.541873,0.517173,0.542382,0.494496,0.495839,0.494935,0.454105,0.448175,0.191784,0.291865,0.452943,0.215080,0.209305,0.254188,0.528866,0.162907,0.289821,0.152955,0.288758,0.185204,0.079861,0.111206
501,34.3721,-119.3977,324.7,1.5,1.2,2003-12-01,2127,Aqua,MODIS,83,6.03,288.5,40.7,D,0,0.201998,0.180857,0.172940,0.198238,0.200584,0.197200,0.187137,0.190918,0.234368,0.229958,0.263456,0.234924,0.210471,0.205260,0.166146,0.287385,0.265315,0.273610,0.241206,0.224440,0.254582,0.117289,0.123318
502,34.3730,-118.9324,321.0,1.6,1.3,2003-12-01,2127,Aqua,MODIS,78,6.03,294.1,30.5,D,0,0.505101,0.495197,0.411390,0.466077,0.396714,0.421494,0.293377,0.245630,0.400504,0.386709,0.511875,0.360263,0.490658,0.521172,0.507995,0.386833,0.560243,0.617564,0.547058,0.592412,0.639464,0.273741,0.236708
503,34.4068,-118.8201,320.5,1.2,1.1,2003-12-02,1859,Terra,MODIS,80,6.03,295.6,17.8,D,0,0.646442,0.560394,0.563045,0.417962,0.456937,0.132210,0.125341,0.167938,0.365193,0.479918,0.556231,0.618909,0.717731,0.754650,0.250713,0.210720,0.185980,0.188012,0.263959,0.350601,0.407509,0.223406,0.236621

In [265]:
verycool2003['NDVI_2005'].mean()

0.3540691747912206

In [266]:
veryhot2017 = veryhot[veryhot['acq_date'].str[:4] == '2017']
veryhot2017

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021,NDVI_2022,NDVI_2023
1195,34.3478,-119.1518,500.0,1.5,1.2,2017-12-05,624,Terra,MODIS,100,6.03,332.3,2928.3,N,0,0.504612,0.513729,0.466855,0.542587,0.522406,0.529900,0.458410,0.457536,0.487782,0.504029,0.505337,0.526227,0.530592,0.549820,0.416165,0.399070,0.468220,0.426002,0.484540,0.406215,0.364557,0.200861,0.215898
1196,34.3494,-119.1357,480.0,1.5,1.2,2017-12-05,624,Terra,MODIS,100,6.03,334.5,2165.8,N,0,0.419956,0.457872,0.345381,0.508620,0.500100,0.601158,0.540712,0.422237,0.596339,0.537083,0.552557,0.552542,0.383130,0.492899,0.459569,0.447404,0.519216,0.332920,0.437511,0.422022,0.317830,0.172237,0.207162
1198,34.3353,-119.1666,446.4,1.5,1.2,2017-12-05,624,Terra,MODIS,100,6.03,304.6,1205.8,N,0,0.276707,0.306210,0.204903,0.300029,0.276069,0.331532,0.303188,0.251148,0.318182,0.313444,0.290878,0.294835,0.248724,0.294331,0.230822,0.270497,0.303394,0.292772,0.286773,0.261299,0.224473,0.138446,0.175915
1213,34.3426,-119.2026,446.5,1.5,1.2,2017-12-05,624,Terra,MODIS,100,6.03,300.7,1204.9,N,0,0.303238,0.360663,0.375890,0.474500,0.451116,0.529536,0.412415,0.466047,0.558209,0.446766,0.480277,0.475936,0.481658,0.393684,0.359200,0.403293,0.489693,0.351801,0.478541,0.463026,0.352903,0.166218,0.225051
1214,34.3444,-119.1852,500.0,1.5,1.2,2017-12-05,624,Terra,MODIS,100,6.03,320.8,2909.9,N,0,0.300442,0.310906,0.230236,0.336612,0.316933,0.343507,0.315758,0.262899,0.306975,0.333917,0.327154,0.339813,0.286461,0.311005,0.274246,0.293597,0.369181,0.272346,0.314026,0.274867,0.236724,0.146224,0.186721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121,34.3937,-119.4021,467.2,1.1,1.0,2017-12-11,1003,Aqua,MODIS,100,6.03,308.5,1068.8,N,0,0.644511,0.665895,0.655841,0.735950,0.730120,0.741151,0.754132,0.704449,0.731603,0.767224,0.767659,0.776268,0.854259,0.847291,0.853144,0.874707,0.808891,0.434110,0.358791,0.334610,0.324314,0.164912,0.174196
2309,34.5188,-119.2055,498.9,1.9,1.3,2017-12-14,2136,Aqua,MODIS,100,6.03,341.1,4003.9,D,0,0.543403,0.580322,0.486202,0.581603,0.560798,0.603429,0.604974,0.524257,0.523596,0.552132,0.587712,0.583591,0.590719,0.611791,0.624336,0.613787,0.590972,0.294420,0.412761,0.424186,0.367878,0.162150,0.161267
2310,34.5170,-119.2252,425.6,1.9,1.3,2017-12-14,2136,Aqua,MODIS,100,6.03,307.4,1106.8,D,0,0.541271,0.544948,0.480513,0.574391,0.553467,0.558164,0.569929,0.512356,0.548892,0.559032,0.564668,0.582956,0.577524,0.584513,0.593750,0.584877,0.575092,0.286908,0.470468,0.497990,0.469081,0.195445,0.182423
2368,34.4645,-119.6228,408.8,3.5,1.8,2017-12-16,1809,Terra,MODIS,100,6.03,303.0,1877.2,D,0,0.315658,0.591617,0.444006,0.632101,0.558756,0.637717,0.622199,0.553389,0.559020,0.599313,0.592668,0.649867,0.614196,0.591999,0.607843,0.615584,0.429266,0.388084,0.506059,0.500829,0.468330,0.157580,0.150665
2386,34.4814,-119.0135,454.9,1.3,1.1,2017-12-16,2124,Aqua,MODIS,100,6.03,400.1,1106.9,D,0,0.543043,0.567623,0.466130,0.592853,0.552230,0.600336,0.554266,0.472616,0.535903,0.568986,0.590740,0.613904,0.580152,0.618594,0.625504,0.604334,0.628330,0.305981,0.423540,0.475922,0.467194,0.230245,0.235819

In [291]:
veryhot2017['NDVI_2021'].mean()

0.4182121222217878

In [292]:
verycool2017 = verycool[verycool['acq_date'].str[:4] == '2017']
verycool2017

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021,NDVI_2022,NDVI_2023
1170,34.3998,-118.9651,321.1,1.1,1.0,2017-01-17,1839,Terra,MODIS,81,6.03,290.5,21.4,D,0,0.387361,0.357676,0.348262,0.377541,0.325716,0.406495,0.447668,0.360058,0.507711,0.623141,0.681479,0.704958,0.817652,0.831269,0.823063,0.329997,0.171598,0.218737,0.256377,0.336500,0.382220,0.221768,0.254768
1171,34.2063,-119.1335,328.7,1.1,1.0,2017-02-23,1858,Terra,MODIS,86,6.03,294.4,29.1,D,2,0.164928,0.183942,0.145987,0.146270,0.092796,0.095035,0.149776,0.147515,0.155629,0.173734,0.151641,0.161017,0.205995,0.186115,0.193244,0.198333,0.209470,0.190446,0.199897,0.215235,0.245526,0.116408,0.108988
1172,34.3114,-119.1320,333.6,1.1,1.0,2017-02-24,2117,Aqua,MODIS,88,6.03,293.5,35.8,D,0,0.422811,0.411578,0.393292,0.416558,0.414781,0.413294,0.383566,0.407174,0.418645,0.434949,0.444042,0.428890,0.478639,0.477839,0.457253,0.477483,0.472761,0.480596,0.484131,0.486239,0.475051,0.247377,0.247168
1173,34.3099,-119.1436,317.4,1.1,1.0,2017-02-24,2117,Aqua,MODIS,76,6.03,292.6,15.2,D,0,0.355206,0.347674,0.355196,0.362412,0.372470,0.394180,0.418653,0.429099,0.462084,0.490782,0.505218,0.535174,0.585035,0.596424,0.638137,0.595651,0.589222,0.628653,0.615956,0.643153,0.638774,0.309548,0.297186
1174,34.3172,-119.1349,310.2,1.9,1.4,2017-02-28,1916,Terra,MODIS,70,6.03,290.6,24.6,D,0,0.639770,0.676958,0.553425,0.472487,0.461074,0.542049,0.583145,0.613651,0.627238,0.655923,0.659147,0.689422,0.715369,0.708970,0.744995,0.535363,0.213984,0.333672,0.438937,0.454781,0.414541,0.230684,0.241392
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2390,34.5084,-119.5788,311.9,1.2,1.1,2017-12-16,2124,Aqua,MODIS,71,6.03,292.7,11.4,D,0,0.305299,0.317741,0.324942,0.339601,0.351806,0.367088,0.367542,0.350821,0.357771,0.401302,0.453605,0.435991,0.415857,0.434103,0.406476,0.385373,0.375557,0.426651,0.480901,0.482533,0.490291,0.201889,0.225239
2393,34.4865,-118.9976,324.3,1.0,1.0,2017-12-17,1852,Terra,MODIS,81,6.03,282.6,22.7,D,0,0.628037,0.607914,0.571782,0.621470,0.622356,0.628828,0.637975,0.597232,0.609242,0.626779,0.646133,0.654423,0.677820,0.674863,0.673113,0.640755,0.648305,0.636419,0.659322,0.680553,0.647539,0.282583,0.279648
2394,34.4881,-119.0085,335.6,1.0,1.0,2017-12-17,1852,Terra,MODIS,90,6.03,285.6,37.5,D,0,0.727805,0.725036,0.678692,0.731372,0.722100,0.723748,0.720905,0.712402,0.652262,0.657005,0.679665,0.696872,0.759011,0.745730,0.749732,0.722325,0.721598,0.592445,0.655918,0.661651,0.622877,0.213961,0.229357
2395,34.4840,-119.0021,328.5,1.0,1.0,2017-12-18,2111,Aqua,MODIS,85,6.03,276.7,28.6,D,0,0.435726,0.451270,0.363646,0.475432,0.459902,0.470072,0.453282,0.383241,0.425470,0.461254,0.464493,0.472304,0.441740,0.457822,0.493936,0.474152,0.498081,0.271245,0.406378,0.456146,0.418079,0.212770,0.205151
2396,34.4824,-119.0131,326.2,1.0,1.0,2017-12-18,2111,Aqua,MODIS,84,6.03,277.9,25.6,D,0,0.471698,0.456886,0.393912,0.483376,0.463972,0.477129,0.473538,0.402334,0.435570,0.489834,0.492575,0.514040,0.474260,0.488483,0.512031,0.505872,0.500326,0.267314,0.378181,0.403712,0.364894,0.193344,0.189200

In [295]:
verycool2017['NDVI_2019'].mean()

0.44455339971843155

In [296]:
veryhot2018 = veryhot[veryhot['acq_date'].str[:4] == '2018']
veryhot2018

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021,NDVI_2022,NDVI_2023
2408,34.2114,-118.7968,500.6,1.5,1.2,2018-11-09,933,Aqua,MODIS,100,6.03,400.1,2930.9,N,0,0.365854,0.329812,0.259467,0.375500,0.365150,0.403110,0.337247,0.245775,0.353056,0.325866,0.387604,0.382281,0.312281,0.360735,0.371953,0.336151,0.374140,0.346438,0.348148,0.448777,0.325250,0.154031,0.160973
2409,34.2223,-118.7954,475.5,1.5,1.2,2018-11-09,933,Aqua,MODIS,100,6.03,310.5,1990.3,N,0,0.204214,0.235324,0.201609,0.208876,0.262079,0.281753,0.234332,0.206643,0.260255,0.256410,0.268379,0.274482,0.253716,0.257230,0.267164,0.249783,0.296313,0.286177,0.318753,0.274538,0.257061,0.110105,0.136062
2417,34.1229,-118.8252,500.0,1.1,1.1,2018-11-09,1858,Terra,MODIS,87,6.03,369.5,1940.5,D,2,0.417897,0.454936,0.387666,0.456163,0.444532,0.514124,0.453441,0.435404,0.477759,0.494648,0.535601,0.478852,0.480469,0.475260,0.526692,0.486897,0.504092,0.500030,0.372854,0.466532,0.339656,0.130950,0.163177
2449,34.0696,-118.8007,476.1,1.1,1.1,2018-11-09,1858,Terra,MODIS,100,6.03,309.5,1348.6,D,0,0.445269,0.438074,0.375736,0.460426,0.436906,0.493953,0.504803,0.371812,0.434475,0.443554,0.424749,0.475407,0.380368,0.375456,0.359378,0.328852,0.382182,0.413302,0.406585,0.466181,0.311745,0.150311,0.211846
2471,34.0787,-118.8806,459.4,1.1,1.1,2018-11-09,1858,Terra,MODIS,100,6.03,304.9,1006.5,D,0,0.465291,0.445658,0.395975,0.494692,0.496272,0.543319,0.493011,0.416138,0.461848,0.526598,0.571313,0.510837,0.474867,0.439274,0.573344,0.488164,0.513619,0.521555,0.356852,0.445081,0.437030,0.164466,0.186445
2477,34.0821,-118.8734,475.2,1.1,1.1,2018-11-09,1858,Terra,MODIS,100,6.03,311.8,1314.7,D,0,0.413639,0.371154,0.308163,0.439810,0.439916,0.455780,0.396593,0.336088,0.386021,0.453033,0.481481,0.441419,0.405063,0.413334,0.504915,0.428065,0.438260,0.461116,0.351093,0.426548,0.365246,0.149647,0.189512
2478,34.0841,-118.8853,500.0,1.1,1.1,2018-11-09,1858,Terra,MODIS,100,6.03,311.1,1928.0,D,0,0.440646,0.385921,0.335606,0.434519,0.412025,0.486417,0.464550,0.363074,0.391129,0.449941,0.450227,0.455894,0.425867,0.384009,0.479588,0.419261,0.445806,0.446756,0.331029,0.424676,0.370022,0.149411,0.187971
2484,34.0915,-118.8713,500.0,1.1,1.1,2018-11-09,1858,Terra,MODIS,100,6.03,339.6,1932.1,D,0,0.335180,0.336453,0.289221,0.318764,0.376632,0.432759,0.390027,0.325883,0.377564,0.385517,0.390405,0.397657,0.349490,0.321376,0.378574,0.336383,0.352282,0.355053,0.289429,0.369904,0.313142,0.137745,0.166267
2485,34.0936,-118.8833,500.0,1.1,1.1,2018-11-09,1858,Terra,MODIS,100,6.03,345.4,1928.0,D,0,0.557673,0.561726,0.452215,0.562708,0.558621,0.618440,0.598948,0.454262,0.547889,0.545455,0.556010,0.559759,0.481439,0.459155,0.563843,0.498257,0.573448,0.565884,0.417441,0.461318,0.403865,0.189808,0.258416
2491,34.1010,-118.8694,500.0,1.1,1.1,2018-11-09,1858,Terra,MODIS,100,6.03,343.9,1929.8,D,0,0.434090,0.446776,0.378450,0.395349,0.426826,0.520564,0.434652,0.394306,0.447111,0.481294,0.468122,0.431814,0.370370,0.385063,0.293208,0.268939,0.338215,0.359237,0.267416,0.279099,0.226525,0.093816,0.103874
2492,34.1031,-118.8816,500.0,1.1,1.1,2018-11-09,1858,Terra,MODIS,100,6.03,326.8,1928.7,D,0,0.637753,0.650761,0.535635,0.655680,0.583630,0.715964,0.660761,0.543475,0.637529,0.660780,0.619048,0.633901,0.573598,0.531602,0.605669,0.532536,0.618329,0.637782,0.671036,0.690940,0.583949,0.243745,0.238043
2519,34.1113,-118.8413,460.0,2.5,1.5,2018-11-09,2035,Aqua,MODIS,100,6.03,331.0,3120.1,D,0,0.372414,0.438293,0.405032,0.401198,0.441699,0.547744,0.371910,0.438778,0.482134,0.485000,0.522727,0.544440,0.496411,0.520774,0.605471,0.560731,0.594636,0.594603,0.282996,0.454429,0.395297,0.136703,0.104381
2522,34.0675,-118.9120,433.4,2.5,1.5,2018-11-09,2035,Aqua,MODIS,87,6.03,317.0,1942.1,D,0,0.395203,0.384494,0.343774,0.398156,0.459622,0.434013,0.423439,0.355126,0.381559,0.421438,0.469172,0.438491,0.376244,0.376610,0.442969,0.377439,0.406933,0.428743,0.313570,0.405166,0.312303,0.153203,0.218803
2523,34.0864,-118.8906,410.8,2.5,1.5,2018-11-09,2035,Aqua,MODIS,100,6.03,310.1,1200.6,D,0,0.371218,0.333333,0.296037,0.394222,0.385709,0.417125,0.354556,0.319328,0.343787,0.418375,0.371349,0.352709,0.357089,0.361678,0.364682,0.331442,0.352729,0.316159,0.365913,0.336605,0.327363,0.146191,0.164992
2524,34.0803,-118.9180,419.8,2.5,1.5,2018-11-09,2035,Aqua,MODIS,100,6.03,307.6,1473.1,D,0,0.551449,0.573130,0.459740,0.585198,0.501034,0.662830,0.606072,0.525110,0.577586,0.548086,0.589348,0.612708,0.505328,0.472929,0.529610,0.457774,0.586156,0.571673,0.528571,0.523450,0.420442,0.198848,0.264377
2539,34.1240,-118.8475,426.8,2.5,1.5,2018-11-09,2035,Aqua,MODIS,100,6.03,314.8,1668.3,D,0,0.396014,0.388601,0.359609,0.433483,0.443147,0.479497,0.415594,0.371517,0.449016,0.438457,0.515408,0.412457,0.413515,0.386406,0.458605,0.405614,0.403717,0.449269,0.328708,0.353058,0.323595,0.100276,0.128955
2580,34.1044,-118.9523,500.0,1.0,1.0,2018-11-11,1846,Terra,MODIS,100,6.03,364.2,1605.6,D,0,0.210893,0.223888,0.191936,0.213572,0.250659,0.236750,0.241755,0.231932,0.233287,0.272271,0.274828,0.243836,0.225015,0.229403,0.219188,0.245130,0.253069,0.273316,0.265306,0.280722,0.234839,0.127381,0.117979
2581,34.1060,-118.9631,500.0,1.0,1.0,2018-11-11,1846,Terra,MODIS,100,6.03,349.5,1608.1,D,0,0.410124,0.428370,0.351566,0.443056,0.420290,0.501320,0.483057,0.340881,0.453694,0.465386,0.466112,0.536215,0.144890,0.227243,0.249100,0.275785,0.311176,0.325859,0.268405,0.322532,0.231059,0.134670,0.149597
2584,34.1133,-118.9504,474.0,1.0,1.0,2018-11-11,1846,Terra,MODIS,100,6.03,348.9,1074.0,D,0,0.321392,0.328322,0.268108,0.333911,0.321885,0.369261,0.351715,0.300660,0.314517,0.333978,0.311927,0.345255,0.230589,0.221825,0.235845,0.243555,0.276057,0.267129,0.174069,0.244949,0.176860,0.165036,0.182294

In [300]:
veryhot2018['NDVI_2021'].mean()

0.3344868037261461

In [302]:
verycool2018 = verycool[verycool['acq_date'].str[:4] == '2018']
verycool2018

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021,NDVI_2022,NDVI_2023
2398,34.3942,-118.8442,311.4,1.0,1.0,2018-02-12,1845,Terra,MODIS,70,6.03,294.6,8.6,D,0,0.619858,0.580741,0.597237,0.644492,0.560361,0.523548,0.596490,0.538050,0.565351,0.572942,0.610537,0.587590,0.278078,0.269019,0.273819,0.250422,0.231938,0.257394,0.255398,0.305829,0.347478,0.221601,0.263206
2399,34.2041,-119.1335,326.5,1.1,1.0,2018-02-26,1858,Terra,MODIS,82,6.03,296.5,23.3,D,2,0.079930,0.109935,0.140566,0.145898,0.156999,0.153402,0.143681,0.144765,0.162370,0.180581,0.181201,0.179882,0.216985,0.205214,0.197245,0.204197,0.211739,0.204499,0.191004,0.190612,0.186792,0.104264,0.106165
2400,34.2134,-119.1313,319.2,1.1,1.0,2018-02-26,1858,Terra,MODIS,75,6.03,294.8,15.0,D,2,0.160170,0.166700,0.160833,0.163575,0.292810,0.194624,0.143342,0.316303,0.168532,0.175524,0.174402,0.168774,0.267425,0.245685,0.241830,0.720978,0.222392,0.184283,0.192891,0.183675,0.040071,0.025265,0.023044
2401,34.3670,-118.9369,325.2,1.0,1.0,2018-02-28,1846,Terra,MODIS,83,6.03,291.7,21.0,D,0,0.554226,0.528618,0.537390,0.612446,0.536873,0.537581,0.491106,0.453078,0.400296,0.422411,0.442596,0.450435,0.485677,0.511218,0.548277,0.487104,0.456973,0.422167,0.472038,0.497168,0.491787,0.259678,0.273338
2402,34.3324,-118.8879,313.2,1.0,1.0,2018-02-28,1846,Terra,MODIS,72,6.03,293.7,8.5,D,0,0.235680,0.231010,0.227385,0.251168,0.267275,0.299712,0.319663,0.355954,0.377293,0.413699,0.410606,0.430654,0.464795,0.434553,0.549333,0.489966,0.466106,0.361888,0.435125,0.355460,0.403790,0.249676,0.231571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2608,34.3116,-119.1738,315.2,1.2,1.1,2018-12-03,2123,Aqua,MODIS,75,6.03,295.5,15.3,D,0,0.282892,0.282766,0.292769,0.317284,0.308712,0.330439,0.287451,0.284056,0.289571,0.287206,0.282794,0.292381,0.464813,0.501339,0.501592,0.496349,0.491329,0.475238,0.475040,0.480866,0.478108,0.262493,0.254282
2609,34.3615,-118.9489,317.5,1.1,1.0,2018-12-07,2059,Aqua,MODIS,78,6.03,288.0,18.3,D,0,0.670304,0.636799,0.621034,0.699895,0.698619,0.672644,0.675161,0.695326,0.733652,0.746050,0.727942,0.701027,0.749200,0.715533,0.397529,0.172320,0.158727,0.164045,0.172521,0.292124,0.304639,0.161025,0.179571
2610,34.3596,-118.9607,330.0,1.1,1.0,2018-12-07,2059,Aqua,MODIS,87,6.03,288.5,34.0,D,0,0.441250,0.432034,0.464229,0.475831,0.468809,0.391697,0.380273,0.360585,0.386504,0.418172,0.421881,0.428304,0.447205,0.435743,0.514318,0.511553,0.466149,0.414332,0.163372,0.271815,0.299952,0.184726,0.202436
2611,34.3547,-119.0307,315.3,1.0,1.0,2018-12-21,2111,Aqua,MODIS,72,6.03,293.9,11.0,D,2,0.156273,0.132131,0.130789,0.168448,0.171079,0.084408,0.093966,0.105658,0.120567,0.150655,0.156063,0.152468,0.143252,0.148236,0.159226,0.174904,0.159523,0.167807,0.197486,0.222801,0.200265,0.076228,0.068978
2612,34.3560,-118.9588,317.8,1.0,1.0,2018-12-21,2111,Aqua,MODIS,76,6.03,294.1,13.4,D,0,0.229769,0.260984,0.206294,0.263163,0.262385,0.330627,0.246764,0.231262,0.314966,0.291537,0.287767,0.319392,0.232093,0.292541,0.250325,0.277051,0.274641,0.284507,0.308075,0.283581,0.234957,0.124149,0.151874

In [308]:
verycool2018['NDVI_2021'].mean()

0.335000225713095

In [309]:
veryhot2013 = veryhot[veryhot['acq_date'].str[:4] == '2013']
veryhot2013

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021,NDVI_2022,NDVI_2023
1041,34.1673,-119.0362,428.8,2.4,1.5,2013-05-02,1815,Terra,MODIS,100,6.03,316.6,1699.9,D,0,0.214016,0.217531,0.165515,0.252747,0.242376,0.201902,0.255304,0.230769,0.278314,0.282492,0.310964,0.272617,0.244459,0.294180,0.266846,0.293454,0.367045,0.327634,0.351673,0.356423,0.346512,0.155621,0.187288
1042,34.1650,-119.0077,419.4,2.4,1.5,2013-05-02,1815,Terra,MODIS,100,6.03,320.3,1380.8,D,0,0.374294,0.390740,0.352669,0.410353,0.371551,0.434140,0.419451,0.334327,0.376875,0.394536,0.442745,0.450622,0.192626,0.261980,0.316245,0.336117,0.424570,0.424899,0.457378,0.461146,0.413434,0.208818,0.254837
1049,34.1786,-119.0074,436.3,2.4,1.5,2013-05-02,1815,Terra,MODIS,100,6.03,327.1,1954.2,D,0,0.232811,0.253100,0.221937,0.265499,0.307451,0.254523,0.262558,0.229962,0.268430,0.285819,0.306216,0.301552,0.164033,0.209884,0.248209,0.292920,0.377358,0.376879,0.412114,0.395191,0.324962,0.110126,0.137482
1070,34.0957,-119.0473,451.6,1.5,1.2,2013-05-03,934,Aqua,MODIS,100,6.03,323.9,1350.7,N,0,0.265496,0.280846,0.223415,0.288558,0.293229,0.306490,0.292817,0.248865,0.276928,0.270077,0.293232,0.286432,0.135634,0.179879,0.213077,0.225271,0.321630,0.316527,0.357700,0.349702,0.263113,0.135162,0.144694
1090,34.1393,-118.9566,500.0,1.1,1.1,2013-05-03,1858,Terra,MODIS,100,6.03,344.0,1894.6,D,0,0.173457,0.377474,0.362858,0.448680,0.420392,0.537487,0.403707,0.359077,0.509965,0.484537,0.512510,0.543599,0.170133,0.215805,0.302752,0.338722,0.430304,0.444715,0.543542,0.578901,0.421582,0.134890,0.164828
1104,34.1486,-118.9541,472.3,1.1,1.1,2013-05-03,1858,Terra,MODIS,100,6.03,316.5,1226.0,D,0,0.341766,0.341716,0.326795,0.377827,0.377615,0.414286,0.375888,0.305493,0.362360,0.425947,0.445156,0.396261,0.213683,0.254132,0.281321,0.312837,0.333447,0.352152,0.395507,0.401432,0.343050,0.187839,0.221401

In [313]:
veryhot2006 = veryhot[veryhot['acq_date'].str[:4] == '2006']
veryhot2006

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021,NDVI_2022,NDVI_2023
698,34.5065,-119.0219,404.1,2.5,1.5,2006-09-18,2142,Aqua,MODIS,100,6.03,316.2,1019.6,D,0,0.290757,0.290866,0.253799,0.295359,0.291275,0.290275,0.262615,0.188844,0.206897,0.230026,0.239268,0.248408,0.251026,0.262701,0.265570,0.267985,0.265204,0.276382,0.278610,0.295104,0.286847,0.146111,0.141557
714,34.5023,-119.0128,500.0,1.0,1.0,2006-09-23,1845,Terra,MODIS,100,6.03,341.4,1615.6,D,0,0.590574,0.582541,0.494144,0.623881,0.605821,0.669753,0.621399,0.520051,0.601230,0.601737,0.638515,0.659082,0.611545,0.698210,0.687500,0.663864,0.693283,0.700943,0.751861,0.724670,0.593171,0.194313,0.203507
715,34.4949,-119.0253,500.0,1.0,1.0,2006-09-23,1845,Terra,MODIS,100,6.03,337.8,1619.1,D,0,0.456439,0.457217,0.442750,0.480185,0.458083,0.478405,0.431861,0.168177,0.223421,0.251528,0.267860,0.287479,0.332827,0.334088,0.365285,0.360653,0.364185,0.379805,0.400088,0.404029,0.387836,0.184966,0.176159
718,34.4934,-119.0144,500.0,1.0,1.0,2006-09-23,1845,Terra,MODIS,100,6.03,326.2,1618.6,D,0,0.713918,0.699109,0.643822,0.706061,0.692870,0.730387,0.676273,0.610362,0.635662,0.669198,0.704923,0.714808,0.739632,0.714463,0.728926,0.702533,0.737500,0.748081,0.795214,0.793656,0.727279,0.302845,0.299191
720,34.4999,-119.0371,399.5,3.8,1.8,2006-09-23,2022,Aqua,MODIS,100,6.03,307.4,1701.9,D,0,0.539446,0.540035,0.485531,0.558302,0.537068,0.575332,0.512071,0.163356,0.280781,0.360648,0.411550,0.439554,0.461184,0.483246,0.505163,0.476765,0.503313,0.508727,0.537769,0.541802,0.471756,0.217467,0.209499
721,34.5089,-119.0330,394.9,3.8,1.8,2006-09-23,2022,Aqua,MODIS,100,6.03,300.5,1529.6,D,0,0.260288,0.264609,0.254798,0.279050,0.274335,0.282768,0.271746,0.172325,0.202223,0.235358,0.236718,0.231124,0.227013,0.228706,0.232021,0.237195,0.235055,0.232523,0.248053,0.245511,0.237026,0.125721,0.124065
723,34.4934,-119.0266,405.9,3.8,1.8,2006-09-23,2022,Aqua,MODIS,100,6.03,311.4,1989.5,D,0,0.437796,0.431055,0.389717,0.430604,0.429578,0.439414,0.392419,0.146886,0.206452,0.237439,0.253669,0.256331,0.278082,0.298924,0.306365,0.311566,0.309947,0.328280,0.347622,0.366542,0.346447,0.175513,0.171322
724,34.4662,-119.0673,383.1,3.8,1.8,2006-09-23,2022,Aqua,MODIS,100,6.03,301.0,1141.7,D,0,0.632519,0.655497,0.527525,0.632918,0.579682,0.700580,0.683132,0.555095,0.648585,0.638636,0.652427,0.689890,0.592063,0.598939,0.616468,0.623935,0.648776,0.366438,0.511132,0.511082,0.400834,0.193030,0.233452
725,34.4836,-119.0662,387.5,3.8,1.8,2006-09-23,2022,Aqua,MODIS,100,6.03,304.8,1280.6,D,0,0.532877,0.556629,0.431767,0.581319,0.509906,0.597632,0.497048,0.220412,0.353714,0.412116,0.482256,0.513809,0.457883,0.480268,0.483095,0.479161,0.522434,0.344388,0.435301,0.450190,0.366073,0.237938,0.243182
726,34.4775,-119.0213,379.6,3.8,1.8,2006-09-23,2022,Aqua,MODIS,100,6.03,300.1,1024.3,D,0,0.501247,0.533405,0.447511,0.565501,0.526785,0.564882,0.536256,0.458963,0.504717,0.534171,0.560278,0.585668,0.587799,0.593901,0.628433,0.593577,0.611366,0.315556,0.430514,0.445228,0.428126,0.184807,0.183457

In [383]:
veryhot2006['NDVI_2011'].mean()

0.46261521726846694

In [327]:
verycool2006 = verycool[verycool['acq_date'].str[:4] == '2006']
verycool2006

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021,NDVI_2022,NDVI_2023
641,34.3893,-118.8324,321.8,1.0,1.0,2006-01-11,2102,Aqua,MODIS,81,6.03,281.8,19.2,D,0,0.128195,0.154952,0.132370,0.152538,0.147693,0.196619,0.203521,0.153799,0.163713,0.206957,0.221867,0.195116,0.225700,0.213486,0.235814,0.235339,0.240576,0.223764,0.263748,0.260606,0.220702,0.101660,0.134255
642,34.3747,-119.0235,313.8,1.3,1.1,2006-01-12,1832,Terra,MODIS,74,6.03,289.4,16.0,D,0,0.421305,0.175360,0.125358,0.184951,0.209438,0.229318,0.141550,0.211214,0.295036,0.379731,0.380243,0.392051,0.468007,0.555092,0.490014,0.539335,0.478201,0.504762,0.501944,0.509362,0.505547,0.180043,0.210233
643,34.3731,-119.0098,313.6,1.3,1.1,2006-01-12,1832,Terra,MODIS,74,6.03,289.3,15.7,D,0,0.327433,0.380251,0.409006,0.518010,0.481282,0.444132,0.483302,0.451735,0.467456,0.559250,0.526457,0.534361,0.563351,0.540508,0.615556,0.604286,0.592627,0.601060,0.596627,0.637458,0.603044,0.283796,0.293654
644,34.3485,-119.0123,321.7,1.1,1.0,2006-01-25,2114,Aqua,MODIS,81,6.03,288.4,20.3,D,0,0.451773,0.428205,0.336722,0.433101,0.269900,0.393046,0.356361,0.310115,0.405592,0.409244,0.450265,0.448087,0.385430,0.430129,0.464591,0.411607,0.483376,0.424678,0.508621,0.494432,0.365206,0.146999,0.165536
645,34.3072,-119.1318,316.7,1.0,1.0,2006-01-26,1844,Terra,MODIS,77,6.03,290.7,14.2,D,0,0.399650,0.393332,0.373570,0.451241,0.400502,0.433051,0.133950,0.286680,0.155229,0.195230,0.203970,0.204554,0.186377,0.280771,0.248474,0.272529,0.431117,0.669336,0.163175,0.184080,0.248859,0.202831,0.208670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
823,34.3697,-118.9375,314.0,1.1,1.0,2006-12-11,2117,Aqua,MODIS,74,6.03,290.9,13.5,D,0,0.387031,0.389830,0.384390,0.395687,0.358979,0.372682,0.347427,0.366410,0.367857,0.373040,0.388926,0.357704,0.261502,0.219152,0.219304,0.283027,0.226673,0.194047,0.208463,0.246306,0.283183,0.121645,0.164074
824,34.3237,-119.0876,323.0,1.0,1.0,2006-12-12,1845,Terra,MODIS,82,6.03,271.9,24.0,D,0,0.250730,0.249433,0.243861,0.263477,0.235763,0.261242,0.268633,0.240022,0.268095,0.306527,0.316567,0.321634,0.395438,0.398444,0.440471,0.420033,0.433228,0.422320,0.498919,0.518639,0.458513,0.185487,0.187794
825,34.3778,-119.1078,312.6,1.0,1.0,2006-12-13,2105,Aqua,MODIS,73,6.03,290.8,9.4,D,0,0.372717,0.398253,0.344556,0.375765,0.365446,0.301417,0.277949,0.285525,0.310537,0.319658,0.385205,0.355634,0.303327,0.315228,0.305696,0.309151,0.295575,0.273177,0.295164,0.315143,0.267942,0.161921,0.195318
826,34.3761,-119.1186,329.4,1.0,1.0,2006-12-13,2105,Aqua,MODIS,86,6.03,291.8,26.8,D,0,0.369818,0.401920,0.299928,0.421187,0.417599,0.404103,0.389166,0.331512,0.374283,0.411551,0.426520,0.425145,0.353029,0.340324,0.333666,0.371704,0.434607,0.269707,0.412713,0.456650,0.332595,0.157411,0.202352
827,34.3720,-119.1138,318.4,1.3,1.1,2006-12-14,1833,Terra,MODIS,78,6.03,295.8,18.3,D,0,0.251540,0.274585,0.201665,0.274239,0.268700,0.276671,0.260796,0.192900,0.269448,0.292870,0.312941,0.286655,0.239315,0.249647,0.241808,0.253509,0.309672,0.224392,0.322965,0.307488,0.240447,0.114814,0.128668

In [400]:
verycool2006['NDVI_2022'].mean()

0.20159789084179983

In [401]:
df.to_csv('final.csv')

In [345]:
df = df.drop(columns=['instrument'])
df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,confidence,version,bright_t31,frp,daynight,type,NDVI_2000,NDVI_2001,NDVI_2002,NDVI_2003,NDVI_2004,NDVI_2005,NDVI_2006,NDVI_2007,NDVI_2008,NDVI_2009,NDVI_2010,NDVI_2011,NDVI_2013,NDVI_2014,NDVI_2015,NDVI_2016,NDVI_2017,NDVI_2018,NDVI_2019,NDVI_2020,NDVI_2021,NDVI_2022,NDVI_2023
0,34.3716,-118.9757,323.1,2.0,1.4,2000-11-28,1929,Terra,80,6.03,295.3,50.3,D,0,0.180210,0.198146,0.207247,0.239830,0.200820,0.055329,0.092687,0.217757,0.121215,0.156365,0.175897,0.189403,0.322997,0.157157,0.164241,0.165583,0.122865,0.122615,0.113362,0.188768,0.245536,0.057681,0.117107
1,34.4592,-118.8596,328.5,1.0,1.0,2000-12-18,1904,Terra,86,6.03,293.6,26.8,D,0,0.396002,0.484689,0.421418,0.525469,0.331276,0.504999,0.439264,0.415397,0.312025,0.415156,0.514810,0.541897,0.451160,0.438695,0.465233,0.413342,0.455834,0.516385,0.562387,0.535325,0.402140,0.202682,0.180689
2,34.4609,-118.8706,324.4,1.0,1.0,2000-12-18,1904,Terra,83,6.03,292.1,21.7,D,0,0.155087,0.212678,0.187728,0.201397,0.210924,0.259487,0.197131,0.206314,0.260396,0.208393,0.202637,0.224645,0.241785,0.237172,0.194229,0.260472,0.206686,0.239091,0.229873,0.225967,0.223771,0.112112,0.123683
3,34.3317,-119.0296,333.3,1.1,1.1,2000-12-25,1910,Terra,88,6.03,290.7,37.7,D,0,0.435763,0.346661,0.433419,0.537519,0.477115,0.532182,0.489130,0.466833,0.568988,0.542271,0.595262,0.520533,0.581933,0.652562,0.680648,0.611448,0.640159,0.535076,0.596800,0.453410,0.317880,0.133303,0.137608
4,34.3298,-119.0179,321.1,1.1,1.1,2000-12-25,1910,Terra,81,6.03,294.7,20.8,D,0,0.168969,0.198264,0.161847,0.180771,0.165291,0.187256,0.156078,0.156980,0.191201,0.193320,0.198579,0.217550,0.176687,0.179003,0.185394,0.176777,0.192174,0.177058,0.227133,0.230021,0.170219,0.116826,0.126685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,34.3057,-119.0683,325.7,2.3,1.5,2023-12-09,2202,Aqua,84,61.03,295.7,71.2,D,0,0.279683,0.308845,0.243872,0.277882,0.232851,0.334356,0.285769,0.255601,0.317380,0.354456,0.388149,0.352871,0.261303,0.295810,0.307121,0.364472,0.415602,0.345153,0.375557,0.269576,0.182947,0.162953,0.194529
2687,34.3045,-119.0845,327.8,2.3,1.5,2023-12-09,2202,Aqua,85,61.03,294.2,80.3,D,0,0.237406,0.262563,0.193867,0.243622,0.248821,0.275026,0.238492,0.206396,0.277364,0.270226,0.251372,0.291879,0.219594,0.250739,0.220316,0.238655,0.290165,0.293229,0.279957,0.237036,0.193116,0.125251,0.173666
2688,34.3039,-119.0913,319.8,2.3,1.5,2023-12-09,2202,Aqua,75,61.03,293.5,49.8,D,0,0.333590,0.356757,0.252774,0.311972,0.235585,0.295847,0.326463,0.264975,0.330906,0.333548,0.351903,0.389155,0.289662,0.288442,0.256296,0.285045,0.312699,0.275955,0.305564,0.296960,0.234675,0.124069,0.148173
2689,34.2857,-119.1862,326.0,1.1,1.0,2024-02-13,2142,Aqua,83,61.03,293.7,23.0,D,2,0.169533,0.191063,0.189498,0.198719,0.207876,0.200573,0.199776,0.209523,0.222448,0.234534,0.238830,0.237687,0.266825,0.251938,0.228474,0.233806,0.254468,0.261212,0.276776,0.261154,0.242923,0.109967,0.123252
2690,34.2872,-119.1750,321.8,1.1,1.0,2024-02-13,2142,Aqua,80,61.03,293.7,18.2,D,2,0.542101,0.502688,0.517409,0.535394,0.516628,0.497478,0.513483,0.495688,0.495911,0.522824,0.489521,0.503036,0.525106,0.532252,0.567150,0.559753,0.559743,0.602640,0.579781,0.578496,0.559918,0.248984,0.251813